// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.messagetypes.v3.proto

package com.ctrip.flight.intl.agg.messagetypes.v3;

public interface MessageHeaderTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.messagetypes.v3.MessageHeaderType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *string SourceAppID = 1 ; //变化 删除
   * </pre>
   *
   * <code>string SessionID = 2;</code>
   */
  java.lang.String getSessionID();
  /**
   * <pre>
   *string SourceAppID = 1 ; //变化 删除
   * </pre>
   *
   * <code>string SessionID = 2;</code>
   */
  com.google.protobuf.ByteString
      getSessionIDBytes();

  /**
   * <code>string TransactionID = 3;</code>
   */
  java.lang.String getTransactionID();
  /**
   * <code>string TransactionID = 3;</code>
   */
  com.google.protobuf.ByteString
      getTransactionIDBytes();

  /**
   * <code>.com.ctrip.flight.intl.agg.messagetypes.v3.ChannelIDType ChannelID = 4;</code>
   */
  int getChannelIDValue();
  /**
   * <code>.com.ctrip.flight.intl.agg.messagetypes.v3.ChannelIDType ChannelID = 4;</code>
   */
  com.ctrip.flight.intl.agg.messagetypes.v3.ChannelIDType getChannelID();

  /**
   * <code>int32 SubChannelID = 5;</code>
   */
  int getSubChannelID();

  /**
   * <code>string CustomerID = 6;</code>
   */
  java.lang.String getCustomerID();
  /**
   * <code>string CustomerID = 6;</code>
   */
  com.google.protobuf.ByteString
      getCustomerIDBytes();

  /**
   * <code>string ClientIP = 8;</code>
   */
  java.lang.String getClientIP();
  /**
   * <code>string ClientIP = 8;</code>
   */
  com.google.protobuf.ByteString
      getClientIPBytes();

  /**
   * <pre>
   *变化 新增设备ID
   * </pre>
   *
   * <code>string VID = 9;</code>
   */
  java.lang.String getVID();
  /**
   * <pre>
   *变化 新增设备ID
   * </pre>
   *
   * <code>string VID = 9;</code>
   */
  com.google.protobuf.ByteString
      getVIDBytes();

  /**
   * <pre>
   *变化 新增RequestID
   * </pre>
   *
   * <code>string RequestID = 10;</code>
   */
  java.lang.String getRequestID();
  /**
   * <pre>
   *变化 新增RequestID
   * </pre>
   *
   * <code>string RequestID = 10;</code>
   */
  com.google.protobuf.ByteString
      getRequestIDBytes();

  /**
   * <pre>
   * 设备系统(ios/android/其他)
   * </pre>
   *
   * <code>string DevicePlatform = 11;</code>
   */
  java.lang.String getDevicePlatform();
  /**
   * <pre>
   * 设备系统(ios/android/其他)
   * </pre>
   *
   * <code>string DevicePlatform = 11;</code>
   */
  com.google.protobuf.ByteString
      getDevicePlatformBytes();

  /**
   * <pre>
   * 设备类型 desktop/mobile/tablet
   * </pre>
   *
   * <code>string DeviceType = 12;</code>
   */
  java.lang.String getDeviceType();
  /**
   * <pre>
   * 设备类型 desktop/mobile/tablet
   * </pre>
   *
   * <code>string DeviceType = 12;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <pre>
   * 平台类型 app/web
   * </pre>
   *
   * <code>string PlatformType = 13;</code>
   */
  java.lang.String getPlatformType();
  /**
   * <pre>
   * 平台类型 app/web
   * </pre>
   *
   * <code>string PlatformType = 13;</code>
   */
  com.google.protobuf.ByteString
      getPlatformTypeBytes();

  /**
   * <pre>
   * 设备操作系统版本号；eg:15.0.2
   * </pre>
   *
   * <code>string DevicePlatformVersion = 14;</code>
   */
  java.lang.String getDevicePlatformVersion();
  /**
   * <pre>
   * 设备操作系统版本号；eg:15.0.2
   * </pre>
   *
   * <code>string DevicePlatformVersion = 14;</code>
   */
  com.google.protobuf.ByteString
      getDevicePlatformVersionBytes();

  /**
   * <pre>
   * ClientID app使用
   * </pre>
   *
   * <code>string ClientID = 15;</code>
   */
  java.lang.String getClientID();
  /**
   * <pre>
   * ClientID app使用
   * </pre>
   *
   * <code>string ClientID = 15;</code>
   */
  com.google.protobuf.ByteString
      getClientIDBytes();

  /**
   * <pre>
   *变化 删除AgentID
   * 调用方场景id; eg:google、ppc、seo等
   * </pre>
   *
   * <code>string AlliancesID = 16;</code>
   */
  java.lang.String getAlliancesID();
  /**
   * <pre>
   *变化 删除AgentID
   * 调用方场景id; eg:google、ppc、seo等
   * </pre>
   *
   * <code>string AlliancesID = 16;</code>
   */
  com.google.protobuf.ByteString
      getAlliancesIDBytes();
}
