// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.additionproduct.v3.proto

package com.ctrip.flight.intl.agg.additionproduct.v3;

public interface CashBackInfoTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.additionproduct.v3.CashBackInfoType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 CashBack = 1;</code>
   */
  int getCashBack();

  /**
   * <code>string CashBackFlag = 2;</code>
   */
  java.lang.String getCashBackFlag();
  /**
   * <code>string CashBackFlag = 2;</code>
   */
  com.google.protobuf.ByteString
      getCashBackFlagBytes();
}
