// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.additionproduct.v3.proto

package com.ctrip.flight.intl.agg.additionproduct.v3;

public interface PackageExtensionFieldTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.additionproduct.v3.PackageExtensionFieldType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ProductActionMode = 1;</code>
   */
  int getProductActionMode();

  /**
   * <code>string ProductRemark = 2;</code>
   */
  java.lang.String getProductRemark();
  /**
   * <code>string ProductRemark = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductRemarkBytes();
}
