// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.additionproduct.v3.proto

package com.ctrip.flight.intl.agg.additionproduct.v3;

/**
 * <pre>
 * 乘客权益信息
 * </pre>
 *
 * Protobuf type {@code com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType}
 */
public  final class ServiceRefType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType)
    ServiceRefTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServiceRefType.newBuilder() to construct.
  private ServiceRefType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServiceRefType() {
    ageType_ = 0;
    brandedFareRef_ = java.util.Collections.emptyList();
    normalServiceRefNum_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServiceRefType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            ageType_ = rawValue;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              brandedFareRef_ = new java.util.ArrayList<com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType>();
              mutable_bitField0_ |= 0x00000002;
            }
            brandedFareRef_.add(
                input.readMessage(com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.parser(), extensionRegistry));
            break;
          }
          case 24: {

            normalServiceRefNum_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        brandedFareRef_ = java.util.Collections.unmodifiableList(brandedFareRef_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.flight.intl.agg.additionproduct.v3.AggAdditionproductV3.internal_static_com_ctrip_flight_intl_agg_additionproduct_v3_ServiceRefType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.flight.intl.agg.additionproduct.v3.AggAdditionproductV3.internal_static_com_ctrip_flight_intl_agg_additionproduct_v3_ServiceRefType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType.class, com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType.Builder.class);
  }

  private int bitField0_;
  public static final int AGETYPE_FIELD_NUMBER = 1;
  private int ageType_;
  /**
   * <pre>
   * 乘客类型
   * </pre>
   *
   * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
   */
  public int getAgeTypeValue() {
    return ageType_;
  }
  /**
   * <pre>
   * 乘客类型
   * </pre>
   *
   * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
   */
  public com.ctrip.flight.intl.agg.flighttypes.v3.AgeType getAgeType() {
    @SuppressWarnings("deprecation")
    com.ctrip.flight.intl.agg.flighttypes.v3.AgeType result = com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.valueOf(ageType_);
    return result == null ? com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.UNRECOGNIZED : result;
  }

  public static final int BRANDEDFAREREF_FIELD_NUMBER = 2;
  private java.util.List<com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType> brandedFareRef_;
  /**
   * <pre>
   * 品牌权益索引列表
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
   */
  public java.util.List<com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType> getBrandedFareRefList() {
    return brandedFareRef_;
  }
  /**
   * <pre>
   * 品牌权益索引列表
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
   */
  public java.util.List<? extends com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefTypeOrBuilder> 
      getBrandedFareRefOrBuilderList() {
    return brandedFareRef_;
  }
  /**
   * <pre>
   * 品牌权益索引列表
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
   */
  public int getBrandedFareRefCount() {
    return brandedFareRef_.size();
  }
  /**
   * <pre>
   * 品牌权益索引列表
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
   */
  public com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType getBrandedFareRef(int index) {
    return brandedFareRef_.get(index);
  }
  /**
   * <pre>
   * 品牌权益索引列表
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
   */
  public com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefTypeOrBuilder getBrandedFareRefOrBuilder(
      int index) {
    return brandedFareRef_.get(index);
  }

  public static final int NORMALSERVICEREFNUM_FIELD_NUMBER = 3;
  private int normalServiceRefNum_;
  /**
   * <pre>
   * 普通权益索引号
   * </pre>
   *
   * <code>int32 NormalServiceRefNum = 3;</code>
   */
  public int getNormalServiceRefNum() {
    return normalServiceRefNum_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ageType_ != com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.ADT.getNumber()) {
      output.writeEnum(1, ageType_);
    }
    for (int i = 0; i < brandedFareRef_.size(); i++) {
      output.writeMessage(2, brandedFareRef_.get(i));
    }
    if (normalServiceRefNum_ != 0) {
      output.writeInt32(3, normalServiceRefNum_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ageType_ != com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.ADT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, ageType_);
    }
    for (int i = 0; i < brandedFareRef_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, brandedFareRef_.get(i));
    }
    if (normalServiceRefNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, normalServiceRefNum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType)) {
      return super.equals(obj);
    }
    com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType other = (com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType) obj;

    boolean result = true;
    result = result && ageType_ == other.ageType_;
    result = result && getBrandedFareRefList()
        .equals(other.getBrandedFareRefList());
    result = result && (getNormalServiceRefNum()
        == other.getNormalServiceRefNum());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + ageType_;
    if (getBrandedFareRefCount() > 0) {
      hash = (37 * hash) + BRANDEDFAREREF_FIELD_NUMBER;
      hash = (53 * hash) + getBrandedFareRefList().hashCode();
    }
    hash = (37 * hash) + NORMALSERVICEREFNUM_FIELD_NUMBER;
    hash = (53 * hash) + getNormalServiceRefNum();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 乘客权益信息
   * </pre>
   *
   * Protobuf type {@code com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType)
      com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.flight.intl.agg.additionproduct.v3.AggAdditionproductV3.internal_static_com_ctrip_flight_intl_agg_additionproduct_v3_ServiceRefType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.flight.intl.agg.additionproduct.v3.AggAdditionproductV3.internal_static_com_ctrip_flight_intl_agg_additionproduct_v3_ServiceRefType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType.class, com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType.Builder.class);
    }

    // Construct using com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBrandedFareRefFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ageType_ = 0;

      if (brandedFareRefBuilder_ == null) {
        brandedFareRef_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        brandedFareRefBuilder_.clear();
      }
      normalServiceRefNum_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.flight.intl.agg.additionproduct.v3.AggAdditionproductV3.internal_static_com_ctrip_flight_intl_agg_additionproduct_v3_ServiceRefType_descriptor;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType getDefaultInstanceForType() {
      return com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType build() {
      com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType buildPartial() {
      com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType result = new com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.ageType_ = ageType_;
      if (brandedFareRefBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          brandedFareRef_ = java.util.Collections.unmodifiableList(brandedFareRef_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.brandedFareRef_ = brandedFareRef_;
      } else {
        result.brandedFareRef_ = brandedFareRefBuilder_.build();
      }
      result.normalServiceRefNum_ = normalServiceRefNum_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType) {
        return mergeFrom((com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType other) {
      if (other == com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType.getDefaultInstance()) return this;
      if (other.ageType_ != 0) {
        setAgeTypeValue(other.getAgeTypeValue());
      }
      if (brandedFareRefBuilder_ == null) {
        if (!other.brandedFareRef_.isEmpty()) {
          if (brandedFareRef_.isEmpty()) {
            brandedFareRef_ = other.brandedFareRef_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBrandedFareRefIsMutable();
            brandedFareRef_.addAll(other.brandedFareRef_);
          }
          onChanged();
        }
      } else {
        if (!other.brandedFareRef_.isEmpty()) {
          if (brandedFareRefBuilder_.isEmpty()) {
            brandedFareRefBuilder_.dispose();
            brandedFareRefBuilder_ = null;
            brandedFareRef_ = other.brandedFareRef_;
            bitField0_ = (bitField0_ & ~0x00000002);
            brandedFareRefBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBrandedFareRefFieldBuilder() : null;
          } else {
            brandedFareRefBuilder_.addAllMessages(other.brandedFareRef_);
          }
        }
      }
      if (other.getNormalServiceRefNum() != 0) {
        setNormalServiceRefNum(other.getNormalServiceRefNum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int ageType_ = 0;
    /**
     * <pre>
     * 乘客类型
     * </pre>
     *
     * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
     */
    public int getAgeTypeValue() {
      return ageType_;
    }
    /**
     * <pre>
     * 乘客类型
     * </pre>
     *
     * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
     */
    public Builder setAgeTypeValue(int value) {
      ageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 乘客类型
     * </pre>
     *
     * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
     */
    public com.ctrip.flight.intl.agg.flighttypes.v3.AgeType getAgeType() {
      @SuppressWarnings("deprecation")
      com.ctrip.flight.intl.agg.flighttypes.v3.AgeType result = com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.valueOf(ageType_);
      return result == null ? com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 乘客类型
     * </pre>
     *
     * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
     */
    public Builder setAgeType(com.ctrip.flight.intl.agg.flighttypes.v3.AgeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      ageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 乘客类型
     * </pre>
     *
     * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
     */
    public Builder clearAgeType() {
      
      ageType_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType> brandedFareRef_ =
      java.util.Collections.emptyList();
    private void ensureBrandedFareRefIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        brandedFareRef_ = new java.util.ArrayList<com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType>(brandedFareRef_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.Builder, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefTypeOrBuilder> brandedFareRefBuilder_;

    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public java.util.List<com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType> getBrandedFareRefList() {
      if (brandedFareRefBuilder_ == null) {
        return java.util.Collections.unmodifiableList(brandedFareRef_);
      } else {
        return brandedFareRefBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public int getBrandedFareRefCount() {
      if (brandedFareRefBuilder_ == null) {
        return brandedFareRef_.size();
      } else {
        return brandedFareRefBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType getBrandedFareRef(int index) {
      if (brandedFareRefBuilder_ == null) {
        return brandedFareRef_.get(index);
      } else {
        return brandedFareRefBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public Builder setBrandedFareRef(
        int index, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType value) {
      if (brandedFareRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBrandedFareRefIsMutable();
        brandedFareRef_.set(index, value);
        onChanged();
      } else {
        brandedFareRefBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public Builder setBrandedFareRef(
        int index, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.Builder builderForValue) {
      if (brandedFareRefBuilder_ == null) {
        ensureBrandedFareRefIsMutable();
        brandedFareRef_.set(index, builderForValue.build());
        onChanged();
      } else {
        brandedFareRefBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public Builder addBrandedFareRef(com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType value) {
      if (brandedFareRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBrandedFareRefIsMutable();
        brandedFareRef_.add(value);
        onChanged();
      } else {
        brandedFareRefBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public Builder addBrandedFareRef(
        int index, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType value) {
      if (brandedFareRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBrandedFareRefIsMutable();
        brandedFareRef_.add(index, value);
        onChanged();
      } else {
        brandedFareRefBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public Builder addBrandedFareRef(
        com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.Builder builderForValue) {
      if (brandedFareRefBuilder_ == null) {
        ensureBrandedFareRefIsMutable();
        brandedFareRef_.add(builderForValue.build());
        onChanged();
      } else {
        brandedFareRefBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public Builder addBrandedFareRef(
        int index, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.Builder builderForValue) {
      if (brandedFareRefBuilder_ == null) {
        ensureBrandedFareRefIsMutable();
        brandedFareRef_.add(index, builderForValue.build());
        onChanged();
      } else {
        brandedFareRefBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public Builder addAllBrandedFareRef(
        java.lang.Iterable<? extends com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType> values) {
      if (brandedFareRefBuilder_ == null) {
        ensureBrandedFareRefIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, brandedFareRef_);
        onChanged();
      } else {
        brandedFareRefBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public Builder clearBrandedFareRef() {
      if (brandedFareRefBuilder_ == null) {
        brandedFareRef_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        brandedFareRefBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public Builder removeBrandedFareRef(int index) {
      if (brandedFareRefBuilder_ == null) {
        ensureBrandedFareRefIsMutable();
        brandedFareRef_.remove(index);
        onChanged();
      } else {
        brandedFareRefBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.Builder getBrandedFareRefBuilder(
        int index) {
      return getBrandedFareRefFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefTypeOrBuilder getBrandedFareRefOrBuilder(
        int index) {
      if (brandedFareRefBuilder_ == null) {
        return brandedFareRef_.get(index);  } else {
        return brandedFareRefBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public java.util.List<? extends com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefTypeOrBuilder> 
         getBrandedFareRefOrBuilderList() {
      if (brandedFareRefBuilder_ != null) {
        return brandedFareRefBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(brandedFareRef_);
      }
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.Builder addBrandedFareRefBuilder() {
      return getBrandedFareRefFieldBuilder().addBuilder(
          com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.getDefaultInstance());
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.Builder addBrandedFareRefBuilder(
        int index) {
      return getBrandedFareRefFieldBuilder().addBuilder(
          index, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.getDefaultInstance());
    }
    /**
     * <pre>
     * 品牌权益索引列表
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType BrandedFareRef = 2;</code>
     */
    public java.util.List<com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.Builder> 
         getBrandedFareRefBuilderList() {
      return getBrandedFareRefFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.Builder, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefTypeOrBuilder> 
        getBrandedFareRefFieldBuilder() {
      if (brandedFareRefBuilder_ == null) {
        brandedFareRefBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefType.Builder, com.ctrip.flight.intl.agg.additionproduct.v3.BrandedFareRefTypeOrBuilder>(
                brandedFareRef_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        brandedFareRef_ = null;
      }
      return brandedFareRefBuilder_;
    }

    private int normalServiceRefNum_ ;
    /**
     * <pre>
     * 普通权益索引号
     * </pre>
     *
     * <code>int32 NormalServiceRefNum = 3;</code>
     */
    public int getNormalServiceRefNum() {
      return normalServiceRefNum_;
    }
    /**
     * <pre>
     * 普通权益索引号
     * </pre>
     *
     * <code>int32 NormalServiceRefNum = 3;</code>
     */
    public Builder setNormalServiceRefNum(int value) {
      
      normalServiceRefNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 普通权益索引号
     * </pre>
     *
     * <code>int32 NormalServiceRefNum = 3;</code>
     */
    public Builder clearNormalServiceRefNum() {
      
      normalServiceRefNum_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType)
  private static final com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType();
  }

  public static com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceRefType>
      PARSER = new com.google.protobuf.AbstractParser<ServiceRefType>() {
    @java.lang.Override
    public ServiceRefType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServiceRefType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServiceRefType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceRefType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.flight.intl.agg.additionproduct.v3.ServiceRefType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

