// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.additionproduct.v3.proto

package com.ctrip.flight.intl.agg.additionproduct.v3;

public interface XProductPreposeInfoTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *前置政策ID
   * </pre>
   *
   * <code>int64 PolicyId = 1;</code>
   */
  long getPolicyId();

  /**
   * <pre>
   *前置X产品类型(1:接送机，2:休息室，3:机加船，4:机加车，7:通用券，11:机加巴士)
   * </pre>
   *
   * <code>int32 ProductType = 2;</code>
   */
  int getProductType();

  /**
   * <pre>
   *行程号
   * </pre>
   *
   * <code>int32 SegmentNo = 3;</code>
   */
  int getSegmentNo();

  /**
   * <pre>
   *营销类型(1赠送,2立减,3定价销售)
   * </pre>
   *
   * <code>int32 MarketingType = 5;</code>
   */
  int getMarketingType();

  /**
   * <pre>
   *营销金额
   * </pre>
   *
   * <code>double MarketingAmount = 6;</code>
   */
  double getMarketingAmount();

  /**
   * <pre>
   *优惠券面价
   * </pre>
   *
   * <code>int32 CouponPrice = 7;</code>
   */
  int getCouponPrice();

  /**
   * <pre>
   *子产品类型
   * </pre>
   *
   * <code>int32 SubProductType = 8;</code>
   */
  int getSubProductType();

  /**
   * <pre>
   *1，通用券-小飞机国际三选一基础配置表主键addtionProductInfoId；
   *2，巴士-邻近城市ID
   *3，接送机-活动Code
   * </pre>
   *
   * <code>string AdditionInfoId = 9;</code>
   */
  java.lang.String getAdditionInfoId();
  /**
   * <pre>
   *1，通用券-小飞机国际三选一基础配置表主键addtionProductInfoId；
   *2，巴士-邻近城市ID
   *3，接送机-活动Code
   * </pre>
   *
   * <code>string AdditionInfoId = 9;</code>
   */
  com.google.protobuf.ByteString
      getAdditionInfoIdBytes();

  /**
   * <pre>
   *1，接送机-车的类型1：奔驰E；2：豪华型；3：舒适型；
   *2，通用券-1：列表页展示；其它：价格维度展示
   * </pre>
   *
   * <code>string AdditionInfoType = 10;</code>
   */
  java.lang.String getAdditionInfoType();
  /**
   * <pre>
   *1，接送机-车的类型1：奔驰E；2：豪华型；3：舒适型；
   *2，通用券-1：列表页展示；其它：价格维度展示
   * </pre>
   *
   * <code>string AdditionInfoType = 10;</code>
   */
  com.google.protobuf.ByteString
      getAdditionInfoTypeBytes();
}
