// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.additionproduct.v3.proto

package com.ctrip.flight.intl.agg.additionproduct.v3;

/**
 * Protobuf type {@code com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType}
 */
public  final class XProductPreposeInfoType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType)
    XProductPreposeInfoTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use XProductPreposeInfoType.newBuilder() to construct.
  private XProductPreposeInfoType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private XProductPreposeInfoType() {
    policyId_ = 0L;
    productType_ = 0;
    segmentNo_ = 0;
    marketingType_ = 0;
    marketingAmount_ = 0D;
    couponPrice_ = 0;
    subProductType_ = 0;
    additionInfoId_ = "";
    additionInfoType_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private XProductPreposeInfoType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            policyId_ = input.readInt64();
            break;
          }
          case 16: {

            productType_ = input.readInt32();
            break;
          }
          case 24: {

            segmentNo_ = input.readInt32();
            break;
          }
          case 40: {

            marketingType_ = input.readInt32();
            break;
          }
          case 49: {

            marketingAmount_ = input.readDouble();
            break;
          }
          case 56: {

            couponPrice_ = input.readInt32();
            break;
          }
          case 64: {

            subProductType_ = input.readInt32();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            additionInfoId_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            additionInfoType_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.flight.intl.agg.additionproduct.v3.AggAdditionproductV3.internal_static_com_ctrip_flight_intl_agg_additionproduct_v3_XProductPreposeInfoType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.flight.intl.agg.additionproduct.v3.AggAdditionproductV3.internal_static_com_ctrip_flight_intl_agg_additionproduct_v3_XProductPreposeInfoType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType.class, com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType.Builder.class);
  }

  public static final int POLICYID_FIELD_NUMBER = 1;
  private long policyId_;
  /**
   * <pre>
   *前置政策ID
   * </pre>
   *
   * <code>int64 PolicyId = 1;</code>
   */
  public long getPolicyId() {
    return policyId_;
  }

  public static final int PRODUCTTYPE_FIELD_NUMBER = 2;
  private int productType_;
  /**
   * <pre>
   *前置X产品类型(1:接送机，2:休息室，3:机加船，4:机加车，7:通用券，11:机加巴士)
   * </pre>
   *
   * <code>int32 ProductType = 2;</code>
   */
  public int getProductType() {
    return productType_;
  }

  public static final int SEGMENTNO_FIELD_NUMBER = 3;
  private int segmentNo_;
  /**
   * <pre>
   *行程号
   * </pre>
   *
   * <code>int32 SegmentNo = 3;</code>
   */
  public int getSegmentNo() {
    return segmentNo_;
  }

  public static final int MARKETINGTYPE_FIELD_NUMBER = 5;
  private int marketingType_;
  /**
   * <pre>
   *营销类型(1赠送,2立减,3定价销售)
   * </pre>
   *
   * <code>int32 MarketingType = 5;</code>
   */
  public int getMarketingType() {
    return marketingType_;
  }

  public static final int MARKETINGAMOUNT_FIELD_NUMBER = 6;
  private double marketingAmount_;
  /**
   * <pre>
   *营销金额
   * </pre>
   *
   * <code>double MarketingAmount = 6;</code>
   */
  public double getMarketingAmount() {
    return marketingAmount_;
  }

  public static final int COUPONPRICE_FIELD_NUMBER = 7;
  private int couponPrice_;
  /**
   * <pre>
   *优惠券面价
   * </pre>
   *
   * <code>int32 CouponPrice = 7;</code>
   */
  public int getCouponPrice() {
    return couponPrice_;
  }

  public static final int SUBPRODUCTTYPE_FIELD_NUMBER = 8;
  private int subProductType_;
  /**
   * <pre>
   *子产品类型
   * </pre>
   *
   * <code>int32 SubProductType = 8;</code>
   */
  public int getSubProductType() {
    return subProductType_;
  }

  public static final int ADDITIONINFOID_FIELD_NUMBER = 9;
  private volatile java.lang.Object additionInfoId_;
  /**
   * <pre>
   *1，通用券-小飞机国际三选一基础配置表主键addtionProductInfoId；
   *2，巴士-邻近城市ID
   *3，接送机-活动Code
   * </pre>
   *
   * <code>string AdditionInfoId = 9;</code>
   */
  public java.lang.String getAdditionInfoId() {
    java.lang.Object ref = additionInfoId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      additionInfoId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *1，通用券-小飞机国际三选一基础配置表主键addtionProductInfoId；
   *2，巴士-邻近城市ID
   *3，接送机-活动Code
   * </pre>
   *
   * <code>string AdditionInfoId = 9;</code>
   */
  public com.google.protobuf.ByteString
      getAdditionInfoIdBytes() {
    java.lang.Object ref = additionInfoId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      additionInfoId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDITIONINFOTYPE_FIELD_NUMBER = 10;
  private volatile java.lang.Object additionInfoType_;
  /**
   * <pre>
   *1，接送机-车的类型1：奔驰E；2：豪华型；3：舒适型；
   *2，通用券-1：列表页展示；其它：价格维度展示
   * </pre>
   *
   * <code>string AdditionInfoType = 10;</code>
   */
  public java.lang.String getAdditionInfoType() {
    java.lang.Object ref = additionInfoType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      additionInfoType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *1，接送机-车的类型1：奔驰E；2：豪华型；3：舒适型；
   *2，通用券-1：列表页展示；其它：价格维度展示
   * </pre>
   *
   * <code>string AdditionInfoType = 10;</code>
   */
  public com.google.protobuf.ByteString
      getAdditionInfoTypeBytes() {
    java.lang.Object ref = additionInfoType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      additionInfoType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (policyId_ != 0L) {
      output.writeInt64(1, policyId_);
    }
    if (productType_ != 0) {
      output.writeInt32(2, productType_);
    }
    if (segmentNo_ != 0) {
      output.writeInt32(3, segmentNo_);
    }
    if (marketingType_ != 0) {
      output.writeInt32(5, marketingType_);
    }
    if (marketingAmount_ != 0D) {
      output.writeDouble(6, marketingAmount_);
    }
    if (couponPrice_ != 0) {
      output.writeInt32(7, couponPrice_);
    }
    if (subProductType_ != 0) {
      output.writeInt32(8, subProductType_);
    }
    if (!getAdditionInfoIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, additionInfoId_);
    }
    if (!getAdditionInfoTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, additionInfoType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (policyId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, policyId_);
    }
    if (productType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, productType_);
    }
    if (segmentNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, segmentNo_);
    }
    if (marketingType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, marketingType_);
    }
    if (marketingAmount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, marketingAmount_);
    }
    if (couponPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, couponPrice_);
    }
    if (subProductType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, subProductType_);
    }
    if (!getAdditionInfoIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, additionInfoId_);
    }
    if (!getAdditionInfoTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, additionInfoType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType)) {
      return super.equals(obj);
    }
    com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType other = (com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType) obj;

    boolean result = true;
    result = result && (getPolicyId()
        == other.getPolicyId());
    result = result && (getProductType()
        == other.getProductType());
    result = result && (getSegmentNo()
        == other.getSegmentNo());
    result = result && (getMarketingType()
        == other.getMarketingType());
    result = result && (
        java.lang.Double.doubleToLongBits(getMarketingAmount())
        == java.lang.Double.doubleToLongBits(
            other.getMarketingAmount()));
    result = result && (getCouponPrice()
        == other.getCouponPrice());
    result = result && (getSubProductType()
        == other.getSubProductType());
    result = result && getAdditionInfoId()
        .equals(other.getAdditionInfoId());
    result = result && getAdditionInfoType()
        .equals(other.getAdditionInfoType());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POLICYID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPolicyId());
    hash = (37 * hash) + PRODUCTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getProductType();
    hash = (37 * hash) + SEGMENTNO_FIELD_NUMBER;
    hash = (53 * hash) + getSegmentNo();
    hash = (37 * hash) + MARKETINGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMarketingType();
    hash = (37 * hash) + MARKETINGAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMarketingAmount()));
    hash = (37 * hash) + COUPONPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getCouponPrice();
    hash = (37 * hash) + SUBPRODUCTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSubProductType();
    hash = (37 * hash) + ADDITIONINFOID_FIELD_NUMBER;
    hash = (53 * hash) + getAdditionInfoId().hashCode();
    hash = (37 * hash) + ADDITIONINFOTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAdditionInfoType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType)
      com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.flight.intl.agg.additionproduct.v3.AggAdditionproductV3.internal_static_com_ctrip_flight_intl_agg_additionproduct_v3_XProductPreposeInfoType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.flight.intl.agg.additionproduct.v3.AggAdditionproductV3.internal_static_com_ctrip_flight_intl_agg_additionproduct_v3_XProductPreposeInfoType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType.class, com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType.Builder.class);
    }

    // Construct using com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      policyId_ = 0L;

      productType_ = 0;

      segmentNo_ = 0;

      marketingType_ = 0;

      marketingAmount_ = 0D;

      couponPrice_ = 0;

      subProductType_ = 0;

      additionInfoId_ = "";

      additionInfoType_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.flight.intl.agg.additionproduct.v3.AggAdditionproductV3.internal_static_com_ctrip_flight_intl_agg_additionproduct_v3_XProductPreposeInfoType_descriptor;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType getDefaultInstanceForType() {
      return com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType build() {
      com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType buildPartial() {
      com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType result = new com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType(this);
      result.policyId_ = policyId_;
      result.productType_ = productType_;
      result.segmentNo_ = segmentNo_;
      result.marketingType_ = marketingType_;
      result.marketingAmount_ = marketingAmount_;
      result.couponPrice_ = couponPrice_;
      result.subProductType_ = subProductType_;
      result.additionInfoId_ = additionInfoId_;
      result.additionInfoType_ = additionInfoType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType) {
        return mergeFrom((com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType other) {
      if (other == com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType.getDefaultInstance()) return this;
      if (other.getPolicyId() != 0L) {
        setPolicyId(other.getPolicyId());
      }
      if (other.getProductType() != 0) {
        setProductType(other.getProductType());
      }
      if (other.getSegmentNo() != 0) {
        setSegmentNo(other.getSegmentNo());
      }
      if (other.getMarketingType() != 0) {
        setMarketingType(other.getMarketingType());
      }
      if (other.getMarketingAmount() != 0D) {
        setMarketingAmount(other.getMarketingAmount());
      }
      if (other.getCouponPrice() != 0) {
        setCouponPrice(other.getCouponPrice());
      }
      if (other.getSubProductType() != 0) {
        setSubProductType(other.getSubProductType());
      }
      if (!other.getAdditionInfoId().isEmpty()) {
        additionInfoId_ = other.additionInfoId_;
        onChanged();
      }
      if (!other.getAdditionInfoType().isEmpty()) {
        additionInfoType_ = other.additionInfoType_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long policyId_ ;
    /**
     * <pre>
     *前置政策ID
     * </pre>
     *
     * <code>int64 PolicyId = 1;</code>
     */
    public long getPolicyId() {
      return policyId_;
    }
    /**
     * <pre>
     *前置政策ID
     * </pre>
     *
     * <code>int64 PolicyId = 1;</code>
     */
    public Builder setPolicyId(long value) {
      
      policyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *前置政策ID
     * </pre>
     *
     * <code>int64 PolicyId = 1;</code>
     */
    public Builder clearPolicyId() {
      
      policyId_ = 0L;
      onChanged();
      return this;
    }

    private int productType_ ;
    /**
     * <pre>
     *前置X产品类型(1:接送机，2:休息室，3:机加船，4:机加车，7:通用券，11:机加巴士)
     * </pre>
     *
     * <code>int32 ProductType = 2;</code>
     */
    public int getProductType() {
      return productType_;
    }
    /**
     * <pre>
     *前置X产品类型(1:接送机，2:休息室，3:机加船，4:机加车，7:通用券，11:机加巴士)
     * </pre>
     *
     * <code>int32 ProductType = 2;</code>
     */
    public Builder setProductType(int value) {
      
      productType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *前置X产品类型(1:接送机，2:休息室，3:机加船，4:机加车，7:通用券，11:机加巴士)
     * </pre>
     *
     * <code>int32 ProductType = 2;</code>
     */
    public Builder clearProductType() {
      
      productType_ = 0;
      onChanged();
      return this;
    }

    private int segmentNo_ ;
    /**
     * <pre>
     *行程号
     * </pre>
     *
     * <code>int32 SegmentNo = 3;</code>
     */
    public int getSegmentNo() {
      return segmentNo_;
    }
    /**
     * <pre>
     *行程号
     * </pre>
     *
     * <code>int32 SegmentNo = 3;</code>
     */
    public Builder setSegmentNo(int value) {
      
      segmentNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *行程号
     * </pre>
     *
     * <code>int32 SegmentNo = 3;</code>
     */
    public Builder clearSegmentNo() {
      
      segmentNo_ = 0;
      onChanged();
      return this;
    }

    private int marketingType_ ;
    /**
     * <pre>
     *营销类型(1赠送,2立减,3定价销售)
     * </pre>
     *
     * <code>int32 MarketingType = 5;</code>
     */
    public int getMarketingType() {
      return marketingType_;
    }
    /**
     * <pre>
     *营销类型(1赠送,2立减,3定价销售)
     * </pre>
     *
     * <code>int32 MarketingType = 5;</code>
     */
    public Builder setMarketingType(int value) {
      
      marketingType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *营销类型(1赠送,2立减,3定价销售)
     * </pre>
     *
     * <code>int32 MarketingType = 5;</code>
     */
    public Builder clearMarketingType() {
      
      marketingType_ = 0;
      onChanged();
      return this;
    }

    private double marketingAmount_ ;
    /**
     * <pre>
     *营销金额
     * </pre>
     *
     * <code>double MarketingAmount = 6;</code>
     */
    public double getMarketingAmount() {
      return marketingAmount_;
    }
    /**
     * <pre>
     *营销金额
     * </pre>
     *
     * <code>double MarketingAmount = 6;</code>
     */
    public Builder setMarketingAmount(double value) {
      
      marketingAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *营销金额
     * </pre>
     *
     * <code>double MarketingAmount = 6;</code>
     */
    public Builder clearMarketingAmount() {
      
      marketingAmount_ = 0D;
      onChanged();
      return this;
    }

    private int couponPrice_ ;
    /**
     * <pre>
     *优惠券面价
     * </pre>
     *
     * <code>int32 CouponPrice = 7;</code>
     */
    public int getCouponPrice() {
      return couponPrice_;
    }
    /**
     * <pre>
     *优惠券面价
     * </pre>
     *
     * <code>int32 CouponPrice = 7;</code>
     */
    public Builder setCouponPrice(int value) {
      
      couponPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *优惠券面价
     * </pre>
     *
     * <code>int32 CouponPrice = 7;</code>
     */
    public Builder clearCouponPrice() {
      
      couponPrice_ = 0;
      onChanged();
      return this;
    }

    private int subProductType_ ;
    /**
     * <pre>
     *子产品类型
     * </pre>
     *
     * <code>int32 SubProductType = 8;</code>
     */
    public int getSubProductType() {
      return subProductType_;
    }
    /**
     * <pre>
     *子产品类型
     * </pre>
     *
     * <code>int32 SubProductType = 8;</code>
     */
    public Builder setSubProductType(int value) {
      
      subProductType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *子产品类型
     * </pre>
     *
     * <code>int32 SubProductType = 8;</code>
     */
    public Builder clearSubProductType() {
      
      subProductType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object additionInfoId_ = "";
    /**
     * <pre>
     *1，通用券-小飞机国际三选一基础配置表主键addtionProductInfoId；
     *2，巴士-邻近城市ID
     *3，接送机-活动Code
     * </pre>
     *
     * <code>string AdditionInfoId = 9;</code>
     */
    public java.lang.String getAdditionInfoId() {
      java.lang.Object ref = additionInfoId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        additionInfoId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *1，通用券-小飞机国际三选一基础配置表主键addtionProductInfoId；
     *2，巴士-邻近城市ID
     *3，接送机-活动Code
     * </pre>
     *
     * <code>string AdditionInfoId = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAdditionInfoIdBytes() {
      java.lang.Object ref = additionInfoId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        additionInfoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *1，通用券-小飞机国际三选一基础配置表主键addtionProductInfoId；
     *2，巴士-邻近城市ID
     *3，接送机-活动Code
     * </pre>
     *
     * <code>string AdditionInfoId = 9;</code>
     */
    public Builder setAdditionInfoId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      additionInfoId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *1，通用券-小飞机国际三选一基础配置表主键addtionProductInfoId；
     *2，巴士-邻近城市ID
     *3，接送机-活动Code
     * </pre>
     *
     * <code>string AdditionInfoId = 9;</code>
     */
    public Builder clearAdditionInfoId() {
      
      additionInfoId_ = getDefaultInstance().getAdditionInfoId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *1，通用券-小飞机国际三选一基础配置表主键addtionProductInfoId；
     *2，巴士-邻近城市ID
     *3，接送机-活动Code
     * </pre>
     *
     * <code>string AdditionInfoId = 9;</code>
     */
    public Builder setAdditionInfoIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      additionInfoId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object additionInfoType_ = "";
    /**
     * <pre>
     *1，接送机-车的类型1：奔驰E；2：豪华型；3：舒适型；
     *2，通用券-1：列表页展示；其它：价格维度展示
     * </pre>
     *
     * <code>string AdditionInfoType = 10;</code>
     */
    public java.lang.String getAdditionInfoType() {
      java.lang.Object ref = additionInfoType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        additionInfoType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *1，接送机-车的类型1：奔驰E；2：豪华型；3：舒适型；
     *2，通用券-1：列表页展示；其它：价格维度展示
     * </pre>
     *
     * <code>string AdditionInfoType = 10;</code>
     */
    public com.google.protobuf.ByteString
        getAdditionInfoTypeBytes() {
      java.lang.Object ref = additionInfoType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        additionInfoType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *1，接送机-车的类型1：奔驰E；2：豪华型；3：舒适型；
     *2，通用券-1：列表页展示；其它：价格维度展示
     * </pre>
     *
     * <code>string AdditionInfoType = 10;</code>
     */
    public Builder setAdditionInfoType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      additionInfoType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *1，接送机-车的类型1：奔驰E；2：豪华型；3：舒适型；
     *2，通用券-1：列表页展示；其它：价格维度展示
     * </pre>
     *
     * <code>string AdditionInfoType = 10;</code>
     */
    public Builder clearAdditionInfoType() {
      
      additionInfoType_ = getDefaultInstance().getAdditionInfoType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *1，接送机-车的类型1：奔驰E；2：豪华型；3：舒适型；
     *2，通用券-1：列表页展示；其它：价格维度展示
     * </pre>
     *
     * <code>string AdditionInfoType = 10;</code>
     */
    public Builder setAdditionInfoTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      additionInfoType_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType)
  private static final com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType();
  }

  public static com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<XProductPreposeInfoType>
      PARSER = new com.google.protobuf.AbstractParser<XProductPreposeInfoType>() {
    @java.lang.Override
    public XProductPreposeInfoType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new XProductPreposeInfoType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<XProductPreposeInfoType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<XProductPreposeInfoType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.flight.intl.agg.additionproduct.v3.XProductPreposeInfoType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

