// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaijiCommonTypes.proto

package com.ctrip.soa;

/**
 * Protobuf type {@code com.ctrip.soa.ErrorDataType}
 */
public  final class ErrorDataType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.soa.ErrorDataType)
    ErrorDataTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ErrorDataType.newBuilder() to construct.
  private ErrorDataType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ErrorDataType() {
    message_ = "";
    errorCode_ = "";
    stackTrace_ = "";
    severityCode_ = 0;
    errorFields_ = java.util.Collections.emptyList();
    errorClassification_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ErrorDataType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            errorCode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            stackTrace_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            severityCode_ = rawValue;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              errorFields_ = new java.util.ArrayList<com.ctrip.soa.ErrorFieldType>();
              mutable_bitField0_ |= 0x00000010;
            }
            errorFields_.add(
                input.readMessage(com.ctrip.soa.ErrorFieldType.parser(), extensionRegistry));
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            errorClassification_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        errorFields_ = java.util.Collections.unmodifiableList(errorFields_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.soa.BaijiCommonTypes.internal_static_com_ctrip_soa_ErrorDataType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.soa.BaijiCommonTypes.internal_static_com_ctrip_soa_ErrorDataType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.soa.ErrorDataType.class, com.ctrip.soa.ErrorDataType.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object message_;
  /**
   * <code>string Message = 1;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string Message = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERRORCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object errorCode_;
  /**
   * <code>string ErrorCode = 2;</code>
   */
  public java.lang.String getErrorCode() {
    java.lang.Object ref = errorCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorCode_ = s;
      return s;
    }
  }
  /**
   * <code>string ErrorCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getErrorCodeBytes() {
    java.lang.Object ref = errorCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STACKTRACE_FIELD_NUMBER = 3;
  private volatile java.lang.Object stackTrace_;
  /**
   * <code>string StackTrace = 3;</code>
   */
  public java.lang.String getStackTrace() {
    java.lang.Object ref = stackTrace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stackTrace_ = s;
      return s;
    }
  }
  /**
   * <code>string StackTrace = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStackTraceBytes() {
    java.lang.Object ref = stackTrace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stackTrace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEVERITYCODE_FIELD_NUMBER = 4;
  private int severityCode_;
  /**
   * <code>.com.ctrip.soa.SeverityCodeType SeverityCode = 4;</code>
   */
  public int getSeverityCodeValue() {
    return severityCode_;
  }
  /**
   * <code>.com.ctrip.soa.SeverityCodeType SeverityCode = 4;</code>
   */
  public com.ctrip.soa.SeverityCodeType getSeverityCode() {
    @SuppressWarnings("deprecation")
    com.ctrip.soa.SeverityCodeType result = com.ctrip.soa.SeverityCodeType.valueOf(severityCode_);
    return result == null ? com.ctrip.soa.SeverityCodeType.UNRECOGNIZED : result;
  }

  public static final int ERRORFIELDS_FIELD_NUMBER = 5;
  private java.util.List<com.ctrip.soa.ErrorFieldType> errorFields_;
  /**
   * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
   */
  public java.util.List<com.ctrip.soa.ErrorFieldType> getErrorFieldsList() {
    return errorFields_;
  }
  /**
   * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
   */
  public java.util.List<? extends com.ctrip.soa.ErrorFieldTypeOrBuilder> 
      getErrorFieldsOrBuilderList() {
    return errorFields_;
  }
  /**
   * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
   */
  public int getErrorFieldsCount() {
    return errorFields_.size();
  }
  /**
   * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
   */
  public com.ctrip.soa.ErrorFieldType getErrorFields(int index) {
    return errorFields_.get(index);
  }
  /**
   * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
   */
  public com.ctrip.soa.ErrorFieldTypeOrBuilder getErrorFieldsOrBuilder(
      int index) {
    return errorFields_.get(index);
  }

  public static final int ERRORCLASSIFICATION_FIELD_NUMBER = 6;
  private int errorClassification_;
  /**
   * <code>.com.ctrip.soa.ErrorClassificationCodeType ErrorClassification = 6;</code>
   */
  public int getErrorClassificationValue() {
    return errorClassification_;
  }
  /**
   * <code>.com.ctrip.soa.ErrorClassificationCodeType ErrorClassification = 6;</code>
   */
  public com.ctrip.soa.ErrorClassificationCodeType getErrorClassification() {
    @SuppressWarnings("deprecation")
    com.ctrip.soa.ErrorClassificationCodeType result = com.ctrip.soa.ErrorClassificationCodeType.valueOf(errorClassification_);
    return result == null ? com.ctrip.soa.ErrorClassificationCodeType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
    }
    if (!getErrorCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorCode_);
    }
    if (!getStackTraceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stackTrace_);
    }
    if (severityCode_ != com.ctrip.soa.SeverityCodeType.SeverityError.getNumber()) {
      output.writeEnum(4, severityCode_);
    }
    for (int i = 0; i < errorFields_.size(); i++) {
      output.writeMessage(5, errorFields_.get(i));
    }
    if (errorClassification_ != com.ctrip.soa.ErrorClassificationCodeType.ServiceError.getNumber()) {
      output.writeEnum(6, errorClassification_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
    }
    if (!getErrorCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorCode_);
    }
    if (!getStackTraceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, stackTrace_);
    }
    if (severityCode_ != com.ctrip.soa.SeverityCodeType.SeverityError.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, severityCode_);
    }
    for (int i = 0; i < errorFields_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, errorFields_.get(i));
    }
    if (errorClassification_ != com.ctrip.soa.ErrorClassificationCodeType.ServiceError.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, errorClassification_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.soa.ErrorDataType)) {
      return super.equals(obj);
    }
    com.ctrip.soa.ErrorDataType other = (com.ctrip.soa.ErrorDataType) obj;

    boolean result = true;
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getErrorCode()
        .equals(other.getErrorCode());
    result = result && getStackTrace()
        .equals(other.getStackTrace());
    result = result && severityCode_ == other.severityCode_;
    result = result && getErrorFieldsList()
        .equals(other.getErrorFieldsList());
    result = result && errorClassification_ == other.errorClassification_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorCode().hashCode();
    hash = (37 * hash) + STACKTRACE_FIELD_NUMBER;
    hash = (53 * hash) + getStackTrace().hashCode();
    hash = (37 * hash) + SEVERITYCODE_FIELD_NUMBER;
    hash = (53 * hash) + severityCode_;
    if (getErrorFieldsCount() > 0) {
      hash = (37 * hash) + ERRORFIELDS_FIELD_NUMBER;
      hash = (53 * hash) + getErrorFieldsList().hashCode();
    }
    hash = (37 * hash) + ERRORCLASSIFICATION_FIELD_NUMBER;
    hash = (53 * hash) + errorClassification_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.soa.ErrorDataType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.soa.ErrorDataType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.soa.ErrorDataType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.soa.ErrorDataType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.soa.ErrorDataType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.soa.ErrorDataType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.soa.ErrorDataType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.soa.ErrorDataType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.soa.ErrorDataType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.soa.ErrorDataType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.soa.ErrorDataType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.soa.ErrorDataType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.soa.ErrorDataType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ctrip.soa.ErrorDataType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.soa.ErrorDataType)
      com.ctrip.soa.ErrorDataTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.soa.BaijiCommonTypes.internal_static_com_ctrip_soa_ErrorDataType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.soa.BaijiCommonTypes.internal_static_com_ctrip_soa_ErrorDataType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.soa.ErrorDataType.class, com.ctrip.soa.ErrorDataType.Builder.class);
    }

    // Construct using com.ctrip.soa.ErrorDataType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getErrorFieldsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      message_ = "";

      errorCode_ = "";

      stackTrace_ = "";

      severityCode_ = 0;

      if (errorFieldsBuilder_ == null) {
        errorFields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        errorFieldsBuilder_.clear();
      }
      errorClassification_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.soa.BaijiCommonTypes.internal_static_com_ctrip_soa_ErrorDataType_descriptor;
    }

    @java.lang.Override
    public com.ctrip.soa.ErrorDataType getDefaultInstanceForType() {
      return com.ctrip.soa.ErrorDataType.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.soa.ErrorDataType build() {
      com.ctrip.soa.ErrorDataType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.soa.ErrorDataType buildPartial() {
      com.ctrip.soa.ErrorDataType result = new com.ctrip.soa.ErrorDataType(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.message_ = message_;
      result.errorCode_ = errorCode_;
      result.stackTrace_ = stackTrace_;
      result.severityCode_ = severityCode_;
      if (errorFieldsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          errorFields_ = java.util.Collections.unmodifiableList(errorFields_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.errorFields_ = errorFields_;
      } else {
        result.errorFields_ = errorFieldsBuilder_.build();
      }
      result.errorClassification_ = errorClassification_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.soa.ErrorDataType) {
        return mergeFrom((com.ctrip.soa.ErrorDataType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.soa.ErrorDataType other) {
      if (other == com.ctrip.soa.ErrorDataType.getDefaultInstance()) return this;
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getErrorCode().isEmpty()) {
        errorCode_ = other.errorCode_;
        onChanged();
      }
      if (!other.getStackTrace().isEmpty()) {
        stackTrace_ = other.stackTrace_;
        onChanged();
      }
      if (other.severityCode_ != 0) {
        setSeverityCodeValue(other.getSeverityCodeValue());
      }
      if (errorFieldsBuilder_ == null) {
        if (!other.errorFields_.isEmpty()) {
          if (errorFields_.isEmpty()) {
            errorFields_ = other.errorFields_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureErrorFieldsIsMutable();
            errorFields_.addAll(other.errorFields_);
          }
          onChanged();
        }
      } else {
        if (!other.errorFields_.isEmpty()) {
          if (errorFieldsBuilder_.isEmpty()) {
            errorFieldsBuilder_.dispose();
            errorFieldsBuilder_ = null;
            errorFields_ = other.errorFields_;
            bitField0_ = (bitField0_ & ~0x00000010);
            errorFieldsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getErrorFieldsFieldBuilder() : null;
          } else {
            errorFieldsBuilder_.addAllMessages(other.errorFields_);
          }
        }
      }
      if (other.errorClassification_ != 0) {
        setErrorClassificationValue(other.getErrorClassificationValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.soa.ErrorDataType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.soa.ErrorDataType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object message_ = "";
    /**
     * <code>string Message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Message = 1;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Message = 1;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string Message = 1;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object errorCode_ = "";
    /**
     * <code>string ErrorCode = 2;</code>
     */
    public java.lang.String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ErrorCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ErrorCode = 2;</code>
     */
    public Builder setErrorCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ErrorCode = 2;</code>
     */
    public Builder clearErrorCode() {
      
      errorCode_ = getDefaultInstance().getErrorCode();
      onChanged();
      return this;
    }
    /**
     * <code>string ErrorCode = 2;</code>
     */
    public Builder setErrorCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stackTrace_ = "";
    /**
     * <code>string StackTrace = 3;</code>
     */
    public java.lang.String getStackTrace() {
      java.lang.Object ref = stackTrace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stackTrace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string StackTrace = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStackTraceBytes() {
      java.lang.Object ref = stackTrace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stackTrace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string StackTrace = 3;</code>
     */
    public Builder setStackTrace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stackTrace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string StackTrace = 3;</code>
     */
    public Builder clearStackTrace() {
      
      stackTrace_ = getDefaultInstance().getStackTrace();
      onChanged();
      return this;
    }
    /**
     * <code>string StackTrace = 3;</code>
     */
    public Builder setStackTraceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stackTrace_ = value;
      onChanged();
      return this;
    }

    private int severityCode_ = 0;
    /**
     * <code>.com.ctrip.soa.SeverityCodeType SeverityCode = 4;</code>
     */
    public int getSeverityCodeValue() {
      return severityCode_;
    }
    /**
     * <code>.com.ctrip.soa.SeverityCodeType SeverityCode = 4;</code>
     */
    public Builder setSeverityCodeValue(int value) {
      severityCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ctrip.soa.SeverityCodeType SeverityCode = 4;</code>
     */
    public com.ctrip.soa.SeverityCodeType getSeverityCode() {
      @SuppressWarnings("deprecation")
      com.ctrip.soa.SeverityCodeType result = com.ctrip.soa.SeverityCodeType.valueOf(severityCode_);
      return result == null ? com.ctrip.soa.SeverityCodeType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.ctrip.soa.SeverityCodeType SeverityCode = 4;</code>
     */
    public Builder setSeverityCode(com.ctrip.soa.SeverityCodeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      severityCode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.ctrip.soa.SeverityCodeType SeverityCode = 4;</code>
     */
    public Builder clearSeverityCode() {
      
      severityCode_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.ctrip.soa.ErrorFieldType> errorFields_ =
      java.util.Collections.emptyList();
    private void ensureErrorFieldsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        errorFields_ = new java.util.ArrayList<com.ctrip.soa.ErrorFieldType>(errorFields_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.soa.ErrorFieldType, com.ctrip.soa.ErrorFieldType.Builder, com.ctrip.soa.ErrorFieldTypeOrBuilder> errorFieldsBuilder_;

    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public java.util.List<com.ctrip.soa.ErrorFieldType> getErrorFieldsList() {
      if (errorFieldsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(errorFields_);
      } else {
        return errorFieldsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public int getErrorFieldsCount() {
      if (errorFieldsBuilder_ == null) {
        return errorFields_.size();
      } else {
        return errorFieldsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public com.ctrip.soa.ErrorFieldType getErrorFields(int index) {
      if (errorFieldsBuilder_ == null) {
        return errorFields_.get(index);
      } else {
        return errorFieldsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public Builder setErrorFields(
        int index, com.ctrip.soa.ErrorFieldType value) {
      if (errorFieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorFieldsIsMutable();
        errorFields_.set(index, value);
        onChanged();
      } else {
        errorFieldsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public Builder setErrorFields(
        int index, com.ctrip.soa.ErrorFieldType.Builder builderForValue) {
      if (errorFieldsBuilder_ == null) {
        ensureErrorFieldsIsMutable();
        errorFields_.set(index, builderForValue.build());
        onChanged();
      } else {
        errorFieldsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public Builder addErrorFields(com.ctrip.soa.ErrorFieldType value) {
      if (errorFieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorFieldsIsMutable();
        errorFields_.add(value);
        onChanged();
      } else {
        errorFieldsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public Builder addErrorFields(
        int index, com.ctrip.soa.ErrorFieldType value) {
      if (errorFieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorFieldsIsMutable();
        errorFields_.add(index, value);
        onChanged();
      } else {
        errorFieldsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public Builder addErrorFields(
        com.ctrip.soa.ErrorFieldType.Builder builderForValue) {
      if (errorFieldsBuilder_ == null) {
        ensureErrorFieldsIsMutable();
        errorFields_.add(builderForValue.build());
        onChanged();
      } else {
        errorFieldsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public Builder addErrorFields(
        int index, com.ctrip.soa.ErrorFieldType.Builder builderForValue) {
      if (errorFieldsBuilder_ == null) {
        ensureErrorFieldsIsMutable();
        errorFields_.add(index, builderForValue.build());
        onChanged();
      } else {
        errorFieldsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public Builder addAllErrorFields(
        java.lang.Iterable<? extends com.ctrip.soa.ErrorFieldType> values) {
      if (errorFieldsBuilder_ == null) {
        ensureErrorFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, errorFields_);
        onChanged();
      } else {
        errorFieldsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public Builder clearErrorFields() {
      if (errorFieldsBuilder_ == null) {
        errorFields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        errorFieldsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public Builder removeErrorFields(int index) {
      if (errorFieldsBuilder_ == null) {
        ensureErrorFieldsIsMutable();
        errorFields_.remove(index);
        onChanged();
      } else {
        errorFieldsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public com.ctrip.soa.ErrorFieldType.Builder getErrorFieldsBuilder(
        int index) {
      return getErrorFieldsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public com.ctrip.soa.ErrorFieldTypeOrBuilder getErrorFieldsOrBuilder(
        int index) {
      if (errorFieldsBuilder_ == null) {
        return errorFields_.get(index);  } else {
        return errorFieldsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public java.util.List<? extends com.ctrip.soa.ErrorFieldTypeOrBuilder> 
         getErrorFieldsOrBuilderList() {
      if (errorFieldsBuilder_ != null) {
        return errorFieldsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(errorFields_);
      }
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public com.ctrip.soa.ErrorFieldType.Builder addErrorFieldsBuilder() {
      return getErrorFieldsFieldBuilder().addBuilder(
          com.ctrip.soa.ErrorFieldType.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public com.ctrip.soa.ErrorFieldType.Builder addErrorFieldsBuilder(
        int index) {
      return getErrorFieldsFieldBuilder().addBuilder(
          index, com.ctrip.soa.ErrorFieldType.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ctrip.soa.ErrorFieldType ErrorFields = 5;</code>
     */
    public java.util.List<com.ctrip.soa.ErrorFieldType.Builder> 
         getErrorFieldsBuilderList() {
      return getErrorFieldsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.soa.ErrorFieldType, com.ctrip.soa.ErrorFieldType.Builder, com.ctrip.soa.ErrorFieldTypeOrBuilder> 
        getErrorFieldsFieldBuilder() {
      if (errorFieldsBuilder_ == null) {
        errorFieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ctrip.soa.ErrorFieldType, com.ctrip.soa.ErrorFieldType.Builder, com.ctrip.soa.ErrorFieldTypeOrBuilder>(
                errorFields_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        errorFields_ = null;
      }
      return errorFieldsBuilder_;
    }

    private int errorClassification_ = 0;
    /**
     * <code>.com.ctrip.soa.ErrorClassificationCodeType ErrorClassification = 6;</code>
     */
    public int getErrorClassificationValue() {
      return errorClassification_;
    }
    /**
     * <code>.com.ctrip.soa.ErrorClassificationCodeType ErrorClassification = 6;</code>
     */
    public Builder setErrorClassificationValue(int value) {
      errorClassification_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.ctrip.soa.ErrorClassificationCodeType ErrorClassification = 6;</code>
     */
    public com.ctrip.soa.ErrorClassificationCodeType getErrorClassification() {
      @SuppressWarnings("deprecation")
      com.ctrip.soa.ErrorClassificationCodeType result = com.ctrip.soa.ErrorClassificationCodeType.valueOf(errorClassification_);
      return result == null ? com.ctrip.soa.ErrorClassificationCodeType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.ctrip.soa.ErrorClassificationCodeType ErrorClassification = 6;</code>
     */
    public Builder setErrorClassification(com.ctrip.soa.ErrorClassificationCodeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      errorClassification_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.ctrip.soa.ErrorClassificationCodeType ErrorClassification = 6;</code>
     */
    public Builder clearErrorClassification() {
      
      errorClassification_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.soa.ErrorDataType)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.soa.ErrorDataType)
  private static final com.ctrip.soa.ErrorDataType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.soa.ErrorDataType();
  }

  public static com.ctrip.soa.ErrorDataType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ErrorDataType>
      PARSER = new com.google.protobuf.AbstractParser<ErrorDataType>() {
    @java.lang.Override
    public ErrorDataType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ErrorDataType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ErrorDataType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ErrorDataType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.soa.ErrorDataType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

