// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.types.searchrequesttype.v3.proto

package com.ctrip.flight.intl.agg.types.searchrequesttype.v3;

public interface RouteSearchControlTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.types.searchrequesttype.v3.RouteSearchControlType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *None=0
   *AllOrigDests=1
   *AllOrigDestsStrict=2
   *AllOrigDestsExtended=3
   *AllFlightProductStrict=4
   *FlightGroupMorePrice=5
   * </pre>
   *
   * <code>int32 RouteSearchMode = 1;</code>
   */
  int getRouteSearchMode();

  /**
   * <code>string RouteSearchToken = 2;</code>
   */
  java.lang.String getRouteSearchToken();
  /**
   * <code>string RouteSearchToken = 2;</code>
   */
  com.google.protobuf.ByteString
      getRouteSearchTokenBytes();

  /**
   * <code>int32 OrigDestSeqID = 3;</code>
   */
  int getOrigDestSeqID();
}
