// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.types.searchrequesttype.v3.proto

package com.ctrip.flight.intl.agg.types.searchrequesttype.v3;

public interface SearchCriteriaTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchCriteriaType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.OrigDestRequestType OrigDestRequest = 1;</code>
   */
  java.util.List<com.ctrip.flight.intl.agg.flighttypes.v3.OrigDestRequestType> 
      getOrigDestRequestList();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.OrigDestRequestType OrigDestRequest = 1;</code>
   */
  com.ctrip.flight.intl.agg.flighttypes.v3.OrigDestRequestType getOrigDestRequest(int index);
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.OrigDestRequestType OrigDestRequest = 1;</code>
   */
  int getOrigDestRequestCount();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.OrigDestRequestType OrigDestRequest = 1;</code>
   */
  java.util.List<? extends com.ctrip.flight.intl.agg.flighttypes.v3.OrigDestRequestTypeOrBuilder> 
      getOrigDestRequestOrBuilderList();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.OrigDestRequestType OrigDestRequest = 1;</code>
   */
  com.ctrip.flight.intl.agg.flighttypes.v3.OrigDestRequestTypeOrBuilder getOrigDestRequestOrBuilder(
      int index);

  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType TravelerRequest = 2;</code>
   */
  java.util.List<com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType> 
      getTravelerRequestList();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType TravelerRequest = 2;</code>
   */
  com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType getTravelerRequest(int index);
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType TravelerRequest = 2;</code>
   */
  int getTravelerRequestCount();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType TravelerRequest = 2;</code>
   */
  java.util.List<? extends com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestTypeOrBuilder> 
      getTravelerRequestOrBuilderList();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType TravelerRequest = 2;</code>
   */
  com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestTypeOrBuilder getTravelerRequestOrBuilder(
      int index);

  /**
   * <pre>
   * 变化 偏好航司名称改为ValidatingCarrier
   * </pre>
   *
   * <code>repeated string ValidatingCarrier = 3;</code>
   */
  java.util.List<java.lang.String>
      getValidatingCarrierList();
  /**
   * <pre>
   * 变化 偏好航司名称改为ValidatingCarrier
   * </pre>
   *
   * <code>repeated string ValidatingCarrier = 3;</code>
   */
  int getValidatingCarrierCount();
  /**
   * <pre>
   * 变化 偏好航司名称改为ValidatingCarrier
   * </pre>
   *
   * <code>repeated string ValidatingCarrier = 3;</code>
   */
  java.lang.String getValidatingCarrier(int index);
  /**
   * <pre>
   * 变化 偏好航司名称改为ValidatingCarrier
   * </pre>
   *
   * <code>repeated string ValidatingCarrier = 3;</code>
   */
  com.google.protobuf.ByteString
      getValidatingCarrierBytes(int index);

  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.CabinClassType CabinClass = 4;</code>
   */
  java.util.List<com.ctrip.flight.intl.agg.flighttypes.v3.CabinClassType> getCabinClassList();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.CabinClassType CabinClass = 4;</code>
   */
  int getCabinClassCount();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.CabinClassType CabinClass = 4;</code>
   */
  com.ctrip.flight.intl.agg.flighttypes.v3.CabinClassType getCabinClass(int index);
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.CabinClassType CabinClass = 4;</code>
   */
  java.util.List<java.lang.Integer>
  getCabinClassValueList();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.CabinClassType CabinClass = 4;</code>
   */
  int getCabinClassValue(int index);

  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.KeyValuePairType ExtensionOption = 6;</code>
   */
  java.util.List<com.ctrip.flight.intl.agg.flighttypes.v3.KeyValuePairType> 
      getExtensionOptionList();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.KeyValuePairType ExtensionOption = 6;</code>
   */
  com.ctrip.flight.intl.agg.flighttypes.v3.KeyValuePairType getExtensionOption(int index);
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.KeyValuePairType ExtensionOption = 6;</code>
   */
  int getExtensionOptionCount();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.KeyValuePairType ExtensionOption = 6;</code>
   */
  java.util.List<? extends com.ctrip.flight.intl.agg.flighttypes.v3.KeyValuePairTypeOrBuilder> 
      getExtensionOptionOrBuilderList();
  /**
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.KeyValuePairType ExtensionOption = 6;</code>
   */
  com.ctrip.flight.intl.agg.flighttypes.v3.KeyValuePairTypeOrBuilder getExtensionOptionOrBuilder(
      int index);

  /**
   * <pre>
   * 币种
   * </pre>
   *
   * <code>string Currency = 7;</code>
   */
  java.lang.String getCurrency();
  /**
   * <pre>
   * 币种
   * </pre>
   *
   * <code>string Currency = 7;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <pre>
   * 高级搜索参数
   * </pre>
   *
   * <code>.com.ctrip.flight.intl.agg.types.searchrequesttype.v3.AdvancedOptionType AdvancedOption = 8;</code>
   */
  boolean hasAdvancedOption();
  /**
   * <pre>
   * 高级搜索参数
   * </pre>
   *
   * <code>.com.ctrip.flight.intl.agg.types.searchrequesttype.v3.AdvancedOptionType AdvancedOption = 8;</code>
   */
  com.ctrip.flight.intl.agg.types.searchrequesttype.v3.AdvancedOptionType getAdvancedOption();
  /**
   * <pre>
   * 高级搜索参数
   * </pre>
   *
   * <code>.com.ctrip.flight.intl.agg.types.searchrequesttype.v3.AdvancedOptionType AdvancedOption = 8;</code>
   */
  com.ctrip.flight.intl.agg.types.searchrequesttype.v3.AdvancedOptionTypeOrBuilder getAdvancedOptionOrBuilder();

  /**
   * <pre>
   * 语种(Locale格式)
   * </pre>
   *
   * <code>string Language = 9;</code>
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * 语种(Locale格式)
   * </pre>
   *
   * <code>string Language = 9;</code>
   */
  com.google.protobuf.ByteString
      getLanguageBytes();
}
