// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.types.searchrequesttype.v3.proto

package com.ctrip.flight.intl.agg.types.searchrequesttype.v3;

public interface SearchRequestTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchRequestType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.ctrip.flight.intl.agg.messagetypes.v3.RequestHeaderType RequestHeader = 1;</code>
   */
  boolean hasRequestHeader();
  /**
   * <code>.com.ctrip.flight.intl.agg.messagetypes.v3.RequestHeaderType RequestHeader = 1;</code>
   */
  com.ctrip.flight.intl.agg.messagetypes.v3.RequestHeaderType getRequestHeader();
  /**
   * <code>.com.ctrip.flight.intl.agg.messagetypes.v3.RequestHeaderType RequestHeader = 1;</code>
   */
  com.ctrip.flight.intl.agg.messagetypes.v3.RequestHeaderTypeOrBuilder getRequestHeaderOrBuilder();

  /**
   * <code>.com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchCriteriaType SearchCriteria = 2;</code>
   */
  boolean hasSearchCriteria();
  /**
   * <code>.com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchCriteriaType SearchCriteria = 2;</code>
   */
  com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchCriteriaType getSearchCriteria();
  /**
   * <code>.com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchCriteriaType SearchCriteria = 2;</code>
   */
  com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchCriteriaTypeOrBuilder getSearchCriteriaOrBuilder();

  /**
   * <pre>
   *	ResultControlType ResultControl = 3 ;
   * </pre>
   *
   * <code>.com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchContextType SearchContext = 4;</code>
   */
  boolean hasSearchContext();
  /**
   * <pre>
   *	ResultControlType ResultControl = 3 ;
   * </pre>
   *
   * <code>.com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchContextType SearchContext = 4;</code>
   */
  com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchContextType getSearchContext();
  /**
   * <pre>
   *	ResultControlType ResultControl = 3 ;
   * </pre>
   *
   * <code>.com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchContextType SearchContext = 4;</code>
   */
  com.ctrip.flight.intl.agg.types.searchrequesttype.v3.SearchContextTypeOrBuilder getSearchContextOrBuilder();
}
