// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

public interface AgencyTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 AgencyID = 1;</code>
   */
  int getAgencyID();

  /**
   * <code>string AgencyCode = 2;</code>
   */
  java.lang.String getAgencyCode();
  /**
   * <code>string AgencyCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getAgencyCodeBytes();

  /**
   * <code>int32 CityID = 3;</code>
   */
  int getCityID();

  /**
   * <code>string CityCode = 4;</code>
   */
  java.lang.String getCityCode();
  /**
   * <code>string CityCode = 4;</code>
   */
  com.google.protobuf.ByteString
      getCityCodeBytes();

  /**
   * <pre>
   * string OfficialName = 6 ;   // 变化 和具体的价格有关系，迁移到PriceInfo
   * </pre>
   *
   * <code>string AgencyName = 5;</code>
   */
  java.lang.String getAgencyName();
  /**
   * <pre>
   * string OfficialName = 6 ;   // 变化 和具体的价格有关系，迁移到PriceInfo
   * </pre>
   *
   * <code>string AgencyName = 5;</code>
   */
  com.google.protobuf.ByteString
      getAgencyNameBytes();
}
