// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

/**
 * Protobuf type {@code com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType}
 */
public  final class AgencyType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType)
    AgencyTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AgencyType.newBuilder() to construct.
  private AgencyType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AgencyType() {
    agencyID_ = 0;
    agencyCode_ = "";
    cityID_ = 0;
    cityCode_ = "";
    agencyName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AgencyType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            agencyID_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            agencyCode_ = s;
            break;
          }
          case 24: {

            cityID_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            cityCode_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            agencyName_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_AgencyType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_AgencyType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType.class, com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType.Builder.class);
  }

  public static final int AGENCYID_FIELD_NUMBER = 1;
  private int agencyID_;
  /**
   * <code>int32 AgencyID = 1;</code>
   */
  public int getAgencyID() {
    return agencyID_;
  }

  public static final int AGENCYCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object agencyCode_;
  /**
   * <code>string AgencyCode = 2;</code>
   */
  public java.lang.String getAgencyCode() {
    java.lang.Object ref = agencyCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agencyCode_ = s;
      return s;
    }
  }
  /**
   * <code>string AgencyCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAgencyCodeBytes() {
    java.lang.Object ref = agencyCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      agencyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITYID_FIELD_NUMBER = 3;
  private int cityID_;
  /**
   * <code>int32 CityID = 3;</code>
   */
  public int getCityID() {
    return cityID_;
  }

  public static final int CITYCODE_FIELD_NUMBER = 4;
  private volatile java.lang.Object cityCode_;
  /**
   * <code>string CityCode = 4;</code>
   */
  public java.lang.String getCityCode() {
    java.lang.Object ref = cityCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cityCode_ = s;
      return s;
    }
  }
  /**
   * <code>string CityCode = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCityCodeBytes() {
    java.lang.Object ref = cityCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cityCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGENCYNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object agencyName_;
  /**
   * <pre>
   * string OfficialName = 6 ;   // 变化 和具体的价格有关系，迁移到PriceInfo
   * </pre>
   *
   * <code>string AgencyName = 5;</code>
   */
  public java.lang.String getAgencyName() {
    java.lang.Object ref = agencyName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agencyName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * string OfficialName = 6 ;   // 变化 和具体的价格有关系，迁移到PriceInfo
   * </pre>
   *
   * <code>string AgencyName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getAgencyNameBytes() {
    java.lang.Object ref = agencyName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      agencyName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (agencyID_ != 0) {
      output.writeInt32(1, agencyID_);
    }
    if (!getAgencyCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, agencyCode_);
    }
    if (cityID_ != 0) {
      output.writeInt32(3, cityID_);
    }
    if (!getCityCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cityCode_);
    }
    if (!getAgencyNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, agencyName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (agencyID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, agencyID_);
    }
    if (!getAgencyCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, agencyCode_);
    }
    if (cityID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, cityID_);
    }
    if (!getCityCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cityCode_);
    }
    if (!getAgencyNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, agencyName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType)) {
      return super.equals(obj);
    }
    com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType other = (com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType) obj;

    boolean result = true;
    result = result && (getAgencyID()
        == other.getAgencyID());
    result = result && getAgencyCode()
        .equals(other.getAgencyCode());
    result = result && (getCityID()
        == other.getCityID());
    result = result && getCityCode()
        .equals(other.getCityCode());
    result = result && getAgencyName()
        .equals(other.getAgencyName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGENCYID_FIELD_NUMBER;
    hash = (53 * hash) + getAgencyID();
    hash = (37 * hash) + AGENCYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getAgencyCode().hashCode();
    hash = (37 * hash) + CITYID_FIELD_NUMBER;
    hash = (53 * hash) + getCityID();
    hash = (37 * hash) + CITYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getCityCode().hashCode();
    hash = (37 * hash) + AGENCYNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAgencyName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType)
      com.ctrip.flight.intl.agg.flighttypes.v3.AgencyTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_AgencyType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_AgencyType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType.class, com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType.Builder.class);
    }

    // Construct using com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      agencyID_ = 0;

      agencyCode_ = "";

      cityID_ = 0;

      cityCode_ = "";

      agencyName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_AgencyType_descriptor;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType getDefaultInstanceForType() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType build() {
      com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType buildPartial() {
      com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType result = new com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType(this);
      result.agencyID_ = agencyID_;
      result.agencyCode_ = agencyCode_;
      result.cityID_ = cityID_;
      result.cityCode_ = cityCode_;
      result.agencyName_ = agencyName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType) {
        return mergeFrom((com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType other) {
      if (other == com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType.getDefaultInstance()) return this;
      if (other.getAgencyID() != 0) {
        setAgencyID(other.getAgencyID());
      }
      if (!other.getAgencyCode().isEmpty()) {
        agencyCode_ = other.agencyCode_;
        onChanged();
      }
      if (other.getCityID() != 0) {
        setCityID(other.getCityID());
      }
      if (!other.getCityCode().isEmpty()) {
        cityCode_ = other.cityCode_;
        onChanged();
      }
      if (!other.getAgencyName().isEmpty()) {
        agencyName_ = other.agencyName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int agencyID_ ;
    /**
     * <code>int32 AgencyID = 1;</code>
     */
    public int getAgencyID() {
      return agencyID_;
    }
    /**
     * <code>int32 AgencyID = 1;</code>
     */
    public Builder setAgencyID(int value) {
      
      agencyID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 AgencyID = 1;</code>
     */
    public Builder clearAgencyID() {
      
      agencyID_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object agencyCode_ = "";
    /**
     * <code>string AgencyCode = 2;</code>
     */
    public java.lang.String getAgencyCode() {
      java.lang.Object ref = agencyCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agencyCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string AgencyCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAgencyCodeBytes() {
      java.lang.Object ref = agencyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string AgencyCode = 2;</code>
     */
    public Builder setAgencyCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      agencyCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string AgencyCode = 2;</code>
     */
    public Builder clearAgencyCode() {
      
      agencyCode_ = getDefaultInstance().getAgencyCode();
      onChanged();
      return this;
    }
    /**
     * <code>string AgencyCode = 2;</code>
     */
    public Builder setAgencyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      agencyCode_ = value;
      onChanged();
      return this;
    }

    private int cityID_ ;
    /**
     * <code>int32 CityID = 3;</code>
     */
    public int getCityID() {
      return cityID_;
    }
    /**
     * <code>int32 CityID = 3;</code>
     */
    public Builder setCityID(int value) {
      
      cityID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 CityID = 3;</code>
     */
    public Builder clearCityID() {
      
      cityID_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object cityCode_ = "";
    /**
     * <code>string CityCode = 4;</code>
     */
    public java.lang.String getCityCode() {
      java.lang.Object ref = cityCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cityCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string CityCode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCityCodeBytes() {
      java.lang.Object ref = cityCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string CityCode = 4;</code>
     */
    public Builder setCityCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cityCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string CityCode = 4;</code>
     */
    public Builder clearCityCode() {
      
      cityCode_ = getDefaultInstance().getCityCode();
      onChanged();
      return this;
    }
    /**
     * <code>string CityCode = 4;</code>
     */
    public Builder setCityCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cityCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object agencyName_ = "";
    /**
     * <pre>
     * string OfficialName = 6 ;   // 变化 和具体的价格有关系，迁移到PriceInfo
     * </pre>
     *
     * <code>string AgencyName = 5;</code>
     */
    public java.lang.String getAgencyName() {
      java.lang.Object ref = agencyName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agencyName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * string OfficialName = 6 ;   // 变化 和具体的价格有关系，迁移到PriceInfo
     * </pre>
     *
     * <code>string AgencyName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAgencyNameBytes() {
      java.lang.Object ref = agencyName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agencyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * string OfficialName = 6 ;   // 变化 和具体的价格有关系，迁移到PriceInfo
     * </pre>
     *
     * <code>string AgencyName = 5;</code>
     */
    public Builder setAgencyName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      agencyName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * string OfficialName = 6 ;   // 变化 和具体的价格有关系，迁移到PriceInfo
     * </pre>
     *
     * <code>string AgencyName = 5;</code>
     */
    public Builder clearAgencyName() {
      
      agencyName_ = getDefaultInstance().getAgencyName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * string OfficialName = 6 ;   // 变化 和具体的价格有关系，迁移到PriceInfo
     * </pre>
     *
     * <code>string AgencyName = 5;</code>
     */
    public Builder setAgencyNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      agencyName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType)
  private static final com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType();
  }

  public static com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgencyType>
      PARSER = new com.google.protobuf.AbstractParser<AgencyType>() {
    @java.lang.Override
    public AgencyType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AgencyType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AgencyType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgencyType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.flight.intl.agg.flighttypes.v3.AgencyType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

