// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

public interface AirlineInfoTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.flighttypes.v3.AirlineInfoType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AirlineCode = 1;</code>
   */
  java.lang.String getAirlineCode();
  /**
   * <code>string AirlineCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getAirlineCodeBytes();

  /**
   * <code>string AirlineName = 2;</code>
   */
  java.lang.String getAirlineName();
  /**
   * <code>string AirlineName = 2;</code>
   */
  com.google.protobuf.ByteString
      getAirlineNameBytes();

  /**
   * <code>string Alliance = 3;</code>
   */
  java.lang.String getAlliance();
  /**
   * <code>string Alliance = 3;</code>
   */
  com.google.protobuf.ByteString
      getAllianceBytes();

  /**
   * <code>bool IsLcc = 4;</code>
   */
  boolean getIsLcc();

  /**
   * <code>string AirlineNameGLB = 5;</code>
   */
  java.lang.String getAirlineNameGLB();
  /**
   * <code>string AirlineNameGLB = 5;</code>
   */
  com.google.protobuf.ByteString
      getAirlineNameGLBBytes();
}
