// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

public interface CacheInfoTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.flighttypes.v3.CacheInfoType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 CacheInfoID = 1;</code>
   */
  int getCacheInfoID();

  /**
   * <code>int32 AgeInMillisecond = 2;</code>
   */
  int getAgeInMillisecond();

  /**
   * <code>string traceId = 3;</code>
   */
  java.lang.String getTraceId();
  /**
   * <code>string traceId = 3;</code>
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();
}
