// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

public interface FareInfoTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.flighttypes.v3.FareInfoType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string FareID = 1;</code>
   */
  java.lang.String getFareID();
  /**
   * <code>string FareID = 1;</code>
   */
  com.google.protobuf.ByteString
      getFareIDBytes();

  /**
   * <code>string FareBasis = 2;</code>
   */
  java.lang.String getFareBasis();
  /**
   * <code>string FareBasis = 2;</code>
   */
  com.google.protobuf.ByteString
      getFareBasisBytes();

  /**
   * <code>int32 FareSource = 3;</code>
   */
  int getFareSource();

  /**
   * <code>string OwnerCarrier = 4;</code>
   */
  java.lang.String getOwnerCarrier();
  /**
   * <code>string OwnerCarrier = 4;</code>
   */
  com.google.protobuf.ByteString
      getOwnerCarrierBytes();

  /**
   * <code>int32 FareType = 5;</code>
   */
  int getFareType();

  /**
   * <code>string AccountCode = 6;</code>
   */
  java.lang.String getAccountCode();
  /**
   * <code>string AccountCode = 6;</code>
   */
  com.google.protobuf.ByteString
      getAccountCodeBytes();

  /**
   * <code>string TicketDesignator = 7;</code>
   */
  java.lang.String getTicketDesignator();
  /**
   * <code>string TicketDesignator = 7;</code>
   */
  com.google.protobuf.ByteString
      getTicketDesignatorBytes();

  /**
   * <code>string TourCode = 8;</code>
   */
  java.lang.String getTourCode();
  /**
   * <code>string TourCode = 8;</code>
   */
  com.google.protobuf.ByteString
      getTourCodeBytes();
}
