// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

public interface KeyValuePairTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.flighttypes.v3.KeyValuePairType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string Key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string Value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string Value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
