// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

public interface ObFeeTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.flighttypes.v3.ObFeeType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ObFee收款方
   * </pre>
   *
   * <code>int32 Payee = 1;</code>
   */
  int getPayee();

  /**
   * <pre>
   * 最小费用
   * </pre>
   *
   * <code>double MinAmount = 2;</code>
   */
  double getMinAmount();

  /**
   * <pre>
   * 最大费用
   * </pre>
   *
   * <code>double MaxAmount = 3;</code>
   */
  double getMaxAmount();

  /**
   * <pre>
   * 对应币种
   * </pre>
   *
   * <code>string Currency = 4;</code>
   */
  java.lang.String getCurrency();
  /**
   * <pre>
   * 对应币种
   * </pre>
   *
   * <code>string Currency = 4;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();
}
