// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

/**
 * Protobuf type {@code com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType}
 */
public  final class PaymentAgencyModelInfoType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType)
    PaymentAgencyModelInfoTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaymentAgencyModelInfoType.newBuilder() to construct.
  private PaymentAgencyModelInfoType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaymentAgencyModelInfoType() {
    creditCardPaymentInfoID_ = java.util.Collections.emptyList();
    paymentDiscountRef_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PaymentAgencyModelInfoType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              creditCardPaymentInfoID_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            creditCardPaymentInfoID_.add(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              creditCardPaymentInfoID_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              creditCardPaymentInfoID_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              paymentDiscountRef_ = new java.util.ArrayList<com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType>();
              mutable_bitField0_ |= 0x00000002;
            }
            paymentDiscountRef_.add(
                input.readMessage(com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        creditCardPaymentInfoID_ = java.util.Collections.unmodifiableList(creditCardPaymentInfoID_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        paymentDiscountRef_ = java.util.Collections.unmodifiableList(paymentDiscountRef_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_PaymentAgencyModelInfoType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_PaymentAgencyModelInfoType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType.class, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType.Builder.class);
  }

  public static final int CREDITCARDPAYMENTINFOID_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> creditCardPaymentInfoID_;
  /**
   * <pre>
   * 信用卡支付的信息索引
   * </pre>
   *
   * <code>repeated int32 CreditCardPaymentInfoID = 1;</code>
   */
  public java.util.List<java.lang.Integer>
      getCreditCardPaymentInfoIDList() {
    return creditCardPaymentInfoID_;
  }
  /**
   * <pre>
   * 信用卡支付的信息索引
   * </pre>
   *
   * <code>repeated int32 CreditCardPaymentInfoID = 1;</code>
   */
  public int getCreditCardPaymentInfoIDCount() {
    return creditCardPaymentInfoID_.size();
  }
  /**
   * <pre>
   * 信用卡支付的信息索引
   * </pre>
   *
   * <code>repeated int32 CreditCardPaymentInfoID = 1;</code>
   */
  public int getCreditCardPaymentInfoID(int index) {
    return creditCardPaymentInfoID_.get(index);
  }
  private int creditCardPaymentInfoIDMemoizedSerializedSize = -1;

  public static final int PAYMENTDISCOUNTREF_FIELD_NUMBER = 2;
  private java.util.List<com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType> paymentDiscountRef_;
  /**
   * <pre>
   * 支付卡让利信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
   */
  public java.util.List<com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType> getPaymentDiscountRefList() {
    return paymentDiscountRef_;
  }
  /**
   * <pre>
   * 支付卡让利信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
   */
  public java.util.List<? extends com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefTypeOrBuilder> 
      getPaymentDiscountRefOrBuilderList() {
    return paymentDiscountRef_;
  }
  /**
   * <pre>
   * 支付卡让利信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
   */
  public int getPaymentDiscountRefCount() {
    return paymentDiscountRef_.size();
  }
  /**
   * <pre>
   * 支付卡让利信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
   */
  public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType getPaymentDiscountRef(int index) {
    return paymentDiscountRef_.get(index);
  }
  /**
   * <pre>
   * 支付卡让利信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
   */
  public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefTypeOrBuilder getPaymentDiscountRefOrBuilder(
      int index) {
    return paymentDiscountRef_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getCreditCardPaymentInfoIDList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(creditCardPaymentInfoIDMemoizedSerializedSize);
    }
    for (int i = 0; i < creditCardPaymentInfoID_.size(); i++) {
      output.writeInt32NoTag(creditCardPaymentInfoID_.get(i));
    }
    for (int i = 0; i < paymentDiscountRef_.size(); i++) {
      output.writeMessage(2, paymentDiscountRef_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < creditCardPaymentInfoID_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(creditCardPaymentInfoID_.get(i));
      }
      size += dataSize;
      if (!getCreditCardPaymentInfoIDList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      creditCardPaymentInfoIDMemoizedSerializedSize = dataSize;
    }
    for (int i = 0; i < paymentDiscountRef_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, paymentDiscountRef_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType)) {
      return super.equals(obj);
    }
    com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType other = (com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType) obj;

    boolean result = true;
    result = result && getCreditCardPaymentInfoIDList()
        .equals(other.getCreditCardPaymentInfoIDList());
    result = result && getPaymentDiscountRefList()
        .equals(other.getPaymentDiscountRefList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCreditCardPaymentInfoIDCount() > 0) {
      hash = (37 * hash) + CREDITCARDPAYMENTINFOID_FIELD_NUMBER;
      hash = (53 * hash) + getCreditCardPaymentInfoIDList().hashCode();
    }
    if (getPaymentDiscountRefCount() > 0) {
      hash = (37 * hash) + PAYMENTDISCOUNTREF_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentDiscountRefList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType)
      com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_PaymentAgencyModelInfoType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_PaymentAgencyModelInfoType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType.class, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType.Builder.class);
    }

    // Construct using com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPaymentDiscountRefFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      creditCardPaymentInfoID_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      if (paymentDiscountRefBuilder_ == null) {
        paymentDiscountRef_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        paymentDiscountRefBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_PaymentAgencyModelInfoType_descriptor;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType getDefaultInstanceForType() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType build() {
      com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType buildPartial() {
      com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType result = new com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        creditCardPaymentInfoID_ = java.util.Collections.unmodifiableList(creditCardPaymentInfoID_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.creditCardPaymentInfoID_ = creditCardPaymentInfoID_;
      if (paymentDiscountRefBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          paymentDiscountRef_ = java.util.Collections.unmodifiableList(paymentDiscountRef_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.paymentDiscountRef_ = paymentDiscountRef_;
      } else {
        result.paymentDiscountRef_ = paymentDiscountRefBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType) {
        return mergeFrom((com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType other) {
      if (other == com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType.getDefaultInstance()) return this;
      if (!other.creditCardPaymentInfoID_.isEmpty()) {
        if (creditCardPaymentInfoID_.isEmpty()) {
          creditCardPaymentInfoID_ = other.creditCardPaymentInfoID_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCreditCardPaymentInfoIDIsMutable();
          creditCardPaymentInfoID_.addAll(other.creditCardPaymentInfoID_);
        }
        onChanged();
      }
      if (paymentDiscountRefBuilder_ == null) {
        if (!other.paymentDiscountRef_.isEmpty()) {
          if (paymentDiscountRef_.isEmpty()) {
            paymentDiscountRef_ = other.paymentDiscountRef_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePaymentDiscountRefIsMutable();
            paymentDiscountRef_.addAll(other.paymentDiscountRef_);
          }
          onChanged();
        }
      } else {
        if (!other.paymentDiscountRef_.isEmpty()) {
          if (paymentDiscountRefBuilder_.isEmpty()) {
            paymentDiscountRefBuilder_.dispose();
            paymentDiscountRefBuilder_ = null;
            paymentDiscountRef_ = other.paymentDiscountRef_;
            bitField0_ = (bitField0_ & ~0x00000002);
            paymentDiscountRefBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPaymentDiscountRefFieldBuilder() : null;
          } else {
            paymentDiscountRefBuilder_.addAllMessages(other.paymentDiscountRef_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> creditCardPaymentInfoID_ = java.util.Collections.emptyList();
    private void ensureCreditCardPaymentInfoIDIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        creditCardPaymentInfoID_ = new java.util.ArrayList<java.lang.Integer>(creditCardPaymentInfoID_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * 信用卡支付的信息索引
     * </pre>
     *
     * <code>repeated int32 CreditCardPaymentInfoID = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getCreditCardPaymentInfoIDList() {
      return java.util.Collections.unmodifiableList(creditCardPaymentInfoID_);
    }
    /**
     * <pre>
     * 信用卡支付的信息索引
     * </pre>
     *
     * <code>repeated int32 CreditCardPaymentInfoID = 1;</code>
     */
    public int getCreditCardPaymentInfoIDCount() {
      return creditCardPaymentInfoID_.size();
    }
    /**
     * <pre>
     * 信用卡支付的信息索引
     * </pre>
     *
     * <code>repeated int32 CreditCardPaymentInfoID = 1;</code>
     */
    public int getCreditCardPaymentInfoID(int index) {
      return creditCardPaymentInfoID_.get(index);
    }
    /**
     * <pre>
     * 信用卡支付的信息索引
     * </pre>
     *
     * <code>repeated int32 CreditCardPaymentInfoID = 1;</code>
     */
    public Builder setCreditCardPaymentInfoID(
        int index, int value) {
      ensureCreditCardPaymentInfoIDIsMutable();
      creditCardPaymentInfoID_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 信用卡支付的信息索引
     * </pre>
     *
     * <code>repeated int32 CreditCardPaymentInfoID = 1;</code>
     */
    public Builder addCreditCardPaymentInfoID(int value) {
      ensureCreditCardPaymentInfoIDIsMutable();
      creditCardPaymentInfoID_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 信用卡支付的信息索引
     * </pre>
     *
     * <code>repeated int32 CreditCardPaymentInfoID = 1;</code>
     */
    public Builder addAllCreditCardPaymentInfoID(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureCreditCardPaymentInfoIDIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, creditCardPaymentInfoID_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 信用卡支付的信息索引
     * </pre>
     *
     * <code>repeated int32 CreditCardPaymentInfoID = 1;</code>
     */
    public Builder clearCreditCardPaymentInfoID() {
      creditCardPaymentInfoID_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private java.util.List<com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType> paymentDiscountRef_ =
      java.util.Collections.emptyList();
    private void ensurePaymentDiscountRefIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        paymentDiscountRef_ = new java.util.ArrayList<com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType>(paymentDiscountRef_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.Builder, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefTypeOrBuilder> paymentDiscountRefBuilder_;

    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public java.util.List<com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType> getPaymentDiscountRefList() {
      if (paymentDiscountRefBuilder_ == null) {
        return java.util.Collections.unmodifiableList(paymentDiscountRef_);
      } else {
        return paymentDiscountRefBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public int getPaymentDiscountRefCount() {
      if (paymentDiscountRefBuilder_ == null) {
        return paymentDiscountRef_.size();
      } else {
        return paymentDiscountRefBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType getPaymentDiscountRef(int index) {
      if (paymentDiscountRefBuilder_ == null) {
        return paymentDiscountRef_.get(index);
      } else {
        return paymentDiscountRefBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public Builder setPaymentDiscountRef(
        int index, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType value) {
      if (paymentDiscountRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePaymentDiscountRefIsMutable();
        paymentDiscountRef_.set(index, value);
        onChanged();
      } else {
        paymentDiscountRefBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public Builder setPaymentDiscountRef(
        int index, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.Builder builderForValue) {
      if (paymentDiscountRefBuilder_ == null) {
        ensurePaymentDiscountRefIsMutable();
        paymentDiscountRef_.set(index, builderForValue.build());
        onChanged();
      } else {
        paymentDiscountRefBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public Builder addPaymentDiscountRef(com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType value) {
      if (paymentDiscountRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePaymentDiscountRefIsMutable();
        paymentDiscountRef_.add(value);
        onChanged();
      } else {
        paymentDiscountRefBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public Builder addPaymentDiscountRef(
        int index, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType value) {
      if (paymentDiscountRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePaymentDiscountRefIsMutable();
        paymentDiscountRef_.add(index, value);
        onChanged();
      } else {
        paymentDiscountRefBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public Builder addPaymentDiscountRef(
        com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.Builder builderForValue) {
      if (paymentDiscountRefBuilder_ == null) {
        ensurePaymentDiscountRefIsMutable();
        paymentDiscountRef_.add(builderForValue.build());
        onChanged();
      } else {
        paymentDiscountRefBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public Builder addPaymentDiscountRef(
        int index, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.Builder builderForValue) {
      if (paymentDiscountRefBuilder_ == null) {
        ensurePaymentDiscountRefIsMutable();
        paymentDiscountRef_.add(index, builderForValue.build());
        onChanged();
      } else {
        paymentDiscountRefBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public Builder addAllPaymentDiscountRef(
        java.lang.Iterable<? extends com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType> values) {
      if (paymentDiscountRefBuilder_ == null) {
        ensurePaymentDiscountRefIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paymentDiscountRef_);
        onChanged();
      } else {
        paymentDiscountRefBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public Builder clearPaymentDiscountRef() {
      if (paymentDiscountRefBuilder_ == null) {
        paymentDiscountRef_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        paymentDiscountRefBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public Builder removePaymentDiscountRef(int index) {
      if (paymentDiscountRefBuilder_ == null) {
        ensurePaymentDiscountRefIsMutable();
        paymentDiscountRef_.remove(index);
        onChanged();
      } else {
        paymentDiscountRefBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.Builder getPaymentDiscountRefBuilder(
        int index) {
      return getPaymentDiscountRefFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefTypeOrBuilder getPaymentDiscountRefOrBuilder(
        int index) {
      if (paymentDiscountRefBuilder_ == null) {
        return paymentDiscountRef_.get(index);  } else {
        return paymentDiscountRefBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public java.util.List<? extends com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefTypeOrBuilder> 
         getPaymentDiscountRefOrBuilderList() {
      if (paymentDiscountRefBuilder_ != null) {
        return paymentDiscountRefBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(paymentDiscountRef_);
      }
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.Builder addPaymentDiscountRefBuilder() {
      return getPaymentDiscountRefFieldBuilder().addBuilder(
          com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.getDefaultInstance());
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.Builder addPaymentDiscountRefBuilder(
        int index) {
      return getPaymentDiscountRefFieldBuilder().addBuilder(
          index, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.getDefaultInstance());
    }
    /**
     * <pre>
     * 支付卡让利信息
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType PaymentDiscountRef = 2;</code>
     */
    public java.util.List<com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.Builder> 
         getPaymentDiscountRefBuilderList() {
      return getPaymentDiscountRefFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.Builder, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefTypeOrBuilder> 
        getPaymentDiscountRefFieldBuilder() {
      if (paymentDiscountRefBuilder_ == null) {
        paymentDiscountRefBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefType.Builder, com.ctrip.flight.intl.agg.flighttypes.v3.PaymentDiscountRefTypeOrBuilder>(
                paymentDiscountRef_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        paymentDiscountRef_ = null;
      }
      return paymentDiscountRefBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType)
  private static final com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType();
  }

  public static com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaymentAgencyModelInfoType>
      PARSER = new com.google.protobuf.AbstractParser<PaymentAgencyModelInfoType>() {
    @java.lang.Override
    public PaymentAgencyModelInfoType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PaymentAgencyModelInfoType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PaymentAgencyModelInfoType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaymentAgencyModelInfoType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.flight.intl.agg.flighttypes.v3.PaymentAgencyModelInfoType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

