// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

/**
 * Protobuf type {@code com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType}
 */
public  final class PriceDetailType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType)
    PriceDetailTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PriceDetailType.newBuilder() to construct.
  private PriceDetailType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PriceDetailType() {
    currency_ = "";
    salePrice_ = 0D;
    tax_ = 0D;
    publishPrice_ = 0D;
    accountPrice_ = 0D;
    netPrice_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PriceDetailType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            currency_ = s;
            break;
          }
          case 17: {

            salePrice_ = input.readDouble();
            break;
          }
          case 25: {

            tax_ = input.readDouble();
            break;
          }
          case 33: {

            publishPrice_ = input.readDouble();
            break;
          }
          case 41: {

            accountPrice_ = input.readDouble();
            break;
          }
          case 49: {

            netPrice_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_PriceDetailType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_PriceDetailType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType.class, com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType.Builder.class);
  }

  public static final int CURRENCY_FIELD_NUMBER = 1;
  private volatile java.lang.Object currency_;
  /**
   * <pre>
   *变化 使用CNY表示人民币币种
   * </pre>
   *
   * <code>string Currency = 1;</code>
   */
  public java.lang.String getCurrency() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currency_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *变化 使用CNY表示人民币币种
   * </pre>
   *
   * <code>string Currency = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALEPRICE_FIELD_NUMBER = 2;
  private double salePrice_;
  /**
   * <code>double SalePrice = 2;</code>
   */
  public double getSalePrice() {
    return salePrice_;
  }

  public static final int TAX_FIELD_NUMBER = 3;
  private double tax_;
  /**
   * <code>double Tax = 3;</code>
   */
  public double getTax() {
    return tax_;
  }

  public static final int PUBLISHPRICE_FIELD_NUMBER = 4;
  private double publishPrice_;
  /**
   * <code>double PublishPrice = 4;</code>
   */
  public double getPublishPrice() {
    return publishPrice_;
  }

  public static final int ACCOUNTPRICE_FIELD_NUMBER = 5;
  private double accountPrice_;
  /**
   * <code>double AccountPrice = 5;</code>
   */
  public double getAccountPrice() {
    return accountPrice_;
  }

  public static final int NETPRICE_FIELD_NUMBER = 6;
  private double netPrice_;
  /**
   * <code>double NetPrice = 6;</code>
   */
  public double getNetPrice() {
    return netPrice_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCurrencyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currency_);
    }
    if (salePrice_ != 0D) {
      output.writeDouble(2, salePrice_);
    }
    if (tax_ != 0D) {
      output.writeDouble(3, tax_);
    }
    if (publishPrice_ != 0D) {
      output.writeDouble(4, publishPrice_);
    }
    if (accountPrice_ != 0D) {
      output.writeDouble(5, accountPrice_);
    }
    if (netPrice_ != 0D) {
      output.writeDouble(6, netPrice_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCurrencyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currency_);
    }
    if (salePrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, salePrice_);
    }
    if (tax_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, tax_);
    }
    if (publishPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, publishPrice_);
    }
    if (accountPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, accountPrice_);
    }
    if (netPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, netPrice_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType)) {
      return super.equals(obj);
    }
    com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType other = (com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType) obj;

    boolean result = true;
    result = result && getCurrency()
        .equals(other.getCurrency());
    result = result && (
        java.lang.Double.doubleToLongBits(getSalePrice())
        == java.lang.Double.doubleToLongBits(
            other.getSalePrice()));
    result = result && (
        java.lang.Double.doubleToLongBits(getTax())
        == java.lang.Double.doubleToLongBits(
            other.getTax()));
    result = result && (
        java.lang.Double.doubleToLongBits(getPublishPrice())
        == java.lang.Double.doubleToLongBits(
            other.getPublishPrice()));
    result = result && (
        java.lang.Double.doubleToLongBits(getAccountPrice())
        == java.lang.Double.doubleToLongBits(
            other.getAccountPrice()));
    result = result && (
        java.lang.Double.doubleToLongBits(getNetPrice())
        == java.lang.Double.doubleToLongBits(
            other.getNetPrice()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrency().hashCode();
    hash = (37 * hash) + SALEPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSalePrice()));
    hash = (37 * hash) + TAX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTax()));
    hash = (37 * hash) + PUBLISHPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPublishPrice()));
    hash = (37 * hash) + ACCOUNTPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAccountPrice()));
    hash = (37 * hash) + NETPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNetPrice()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType)
      com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_PriceDetailType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_PriceDetailType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType.class, com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType.Builder.class);
    }

    // Construct using com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currency_ = "";

      salePrice_ = 0D;

      tax_ = 0D;

      publishPrice_ = 0D;

      accountPrice_ = 0D;

      netPrice_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_PriceDetailType_descriptor;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType getDefaultInstanceForType() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType build() {
      com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType buildPartial() {
      com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType result = new com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType(this);
      result.currency_ = currency_;
      result.salePrice_ = salePrice_;
      result.tax_ = tax_;
      result.publishPrice_ = publishPrice_;
      result.accountPrice_ = accountPrice_;
      result.netPrice_ = netPrice_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType) {
        return mergeFrom((com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType other) {
      if (other == com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType.getDefaultInstance()) return this;
      if (!other.getCurrency().isEmpty()) {
        currency_ = other.currency_;
        onChanged();
      }
      if (other.getSalePrice() != 0D) {
        setSalePrice(other.getSalePrice());
      }
      if (other.getTax() != 0D) {
        setTax(other.getTax());
      }
      if (other.getPublishPrice() != 0D) {
        setPublishPrice(other.getPublishPrice());
      }
      if (other.getAccountPrice() != 0D) {
        setAccountPrice(other.getAccountPrice());
      }
      if (other.getNetPrice() != 0D) {
        setNetPrice(other.getNetPrice());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object currency_ = "";
    /**
     * <pre>
     *变化 使用CNY表示人民币币种
     * </pre>
     *
     * <code>string Currency = 1;</code>
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *变化 使用CNY表示人民币币种
     * </pre>
     *
     * <code>string Currency = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *变化 使用CNY表示人民币币种
     * </pre>
     *
     * <code>string Currency = 1;</code>
     */
    public Builder setCurrency(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currency_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *变化 使用CNY表示人民币币种
     * </pre>
     *
     * <code>string Currency = 1;</code>
     */
    public Builder clearCurrency() {
      
      currency_ = getDefaultInstance().getCurrency();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *变化 使用CNY表示人民币币种
     * </pre>
     *
     * <code>string Currency = 1;</code>
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currency_ = value;
      onChanged();
      return this;
    }

    private double salePrice_ ;
    /**
     * <code>double SalePrice = 2;</code>
     */
    public double getSalePrice() {
      return salePrice_;
    }
    /**
     * <code>double SalePrice = 2;</code>
     */
    public Builder setSalePrice(double value) {
      
      salePrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double SalePrice = 2;</code>
     */
    public Builder clearSalePrice() {
      
      salePrice_ = 0D;
      onChanged();
      return this;
    }

    private double tax_ ;
    /**
     * <code>double Tax = 3;</code>
     */
    public double getTax() {
      return tax_;
    }
    /**
     * <code>double Tax = 3;</code>
     */
    public Builder setTax(double value) {
      
      tax_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double Tax = 3;</code>
     */
    public Builder clearTax() {
      
      tax_ = 0D;
      onChanged();
      return this;
    }

    private double publishPrice_ ;
    /**
     * <code>double PublishPrice = 4;</code>
     */
    public double getPublishPrice() {
      return publishPrice_;
    }
    /**
     * <code>double PublishPrice = 4;</code>
     */
    public Builder setPublishPrice(double value) {
      
      publishPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double PublishPrice = 4;</code>
     */
    public Builder clearPublishPrice() {
      
      publishPrice_ = 0D;
      onChanged();
      return this;
    }

    private double accountPrice_ ;
    /**
     * <code>double AccountPrice = 5;</code>
     */
    public double getAccountPrice() {
      return accountPrice_;
    }
    /**
     * <code>double AccountPrice = 5;</code>
     */
    public Builder setAccountPrice(double value) {
      
      accountPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double AccountPrice = 5;</code>
     */
    public Builder clearAccountPrice() {
      
      accountPrice_ = 0D;
      onChanged();
      return this;
    }

    private double netPrice_ ;
    /**
     * <code>double NetPrice = 6;</code>
     */
    public double getNetPrice() {
      return netPrice_;
    }
    /**
     * <code>double NetPrice = 6;</code>
     */
    public Builder setNetPrice(double value) {
      
      netPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double NetPrice = 6;</code>
     */
    public Builder clearNetPrice() {
      
      netPrice_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType)
  private static final com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType();
  }

  public static com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PriceDetailType>
      PARSER = new com.google.protobuf.AbstractParser<PriceDetailType>() {
    @java.lang.Override
    public PriceDetailType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PriceDetailType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PriceDetailType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PriceDetailType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.flight.intl.agg.flighttypes.v3.PriceDetailType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

