// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

public interface ServiceFeeTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.flighttypes.v3.ServiceFeeType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 服务费种类 1.携程订位服务费
   * </pre>
   *
   * <code>int32 Category = 1;</code>
   */
  int getCategory();

  /**
   * <pre>
   * 服务费收款方
   * </pre>
   *
   * <code>int32 Payee = 2;</code>
   */
  int getPayee();

  /**
   * <pre>
   * 金额值
   * </pre>
   *
   * <code>double Amount = 3;</code>
   */
  double getAmount();
}
