// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

public interface TicketingTimeLimitTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.flighttypes.v3.TicketingTimeLimitType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *出票保护时限类型，0:订单生成出票单后,1:航班起飞时间前
   * </pre>
   *
   * <code>int32 TimeLimitType = 1;</code>
   */
  int getTimeLimitType();

  /**
   * <code>int32 LimitTime = 2;</code>
   */
  int getLimitTime();

  /**
   * <code>double AverageTicketingTime = 3;</code>
   */
  double getAverageTicketingTime();
}
