// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

/**
 * Protobuf type {@code com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType}
 */
public  final class TravelerRequestType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType)
    TravelerRequestTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TravelerRequestType.newBuilder() to construct.
  private TravelerRequestType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TravelerRequestType() {
    ageType_ = 0;
    travelerCount_ = 0;
    nationality_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TravelerRequestType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            ageType_ = rawValue;
            break;
          }
          case 16: {

            travelerCount_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nationality_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_TravelerRequestType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_TravelerRequestType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType.class, com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType.Builder.class);
  }

  public static final int AGETYPE_FIELD_NUMBER = 1;
  private int ageType_;
  /**
   * <pre>
   * 不支持指定ADT
   * </pre>
   *
   * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
   */
  public int getAgeTypeValue() {
    return ageType_;
  }
  /**
   * <pre>
   * 不支持指定ADT
   * </pre>
   *
   * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
   */
  public com.ctrip.flight.intl.agg.flighttypes.v3.AgeType getAgeType() {
    @SuppressWarnings("deprecation")
    com.ctrip.flight.intl.agg.flighttypes.v3.AgeType result = com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.valueOf(ageType_);
    return result == null ? com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.UNRECOGNIZED : result;
  }

  public static final int TRAVELERCOUNT_FIELD_NUMBER = 2;
  private int travelerCount_;
  /**
   * <code>int32 TravelerCount = 2;</code>
   */
  public int getTravelerCount() {
    return travelerCount_;
  }

  public static final int NATIONALITY_FIELD_NUMBER = 3;
  private volatile java.lang.Object nationality_;
  /**
   * <code>string Nationality = 3;</code>
   */
  public java.lang.String getNationality() {
    java.lang.Object ref = nationality_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nationality_ = s;
      return s;
    }
  }
  /**
   * <code>string Nationality = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNationalityBytes() {
    java.lang.Object ref = nationality_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nationality_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ageType_ != com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.ADT.getNumber()) {
      output.writeEnum(1, ageType_);
    }
    if (travelerCount_ != 0) {
      output.writeInt32(2, travelerCount_);
    }
    if (!getNationalityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nationality_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ageType_ != com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.ADT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, ageType_);
    }
    if (travelerCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, travelerCount_);
    }
    if (!getNationalityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nationality_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType)) {
      return super.equals(obj);
    }
    com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType other = (com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType) obj;

    boolean result = true;
    result = result && ageType_ == other.ageType_;
    result = result && (getTravelerCount()
        == other.getTravelerCount());
    result = result && getNationality()
        .equals(other.getNationality());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + ageType_;
    hash = (37 * hash) + TRAVELERCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTravelerCount();
    hash = (37 * hash) + NATIONALITY_FIELD_NUMBER;
    hash = (53 * hash) + getNationality().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType)
      com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_TravelerRequestType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_TravelerRequestType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType.class, com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType.Builder.class);
    }

    // Construct using com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ageType_ = 0;

      travelerCount_ = 0;

      nationality_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.internal_static_com_ctrip_flight_intl_agg_flighttypes_v3_TravelerRequestType_descriptor;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType getDefaultInstanceForType() {
      return com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType build() {
      com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType buildPartial() {
      com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType result = new com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType(this);
      result.ageType_ = ageType_;
      result.travelerCount_ = travelerCount_;
      result.nationality_ = nationality_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType) {
        return mergeFrom((com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType other) {
      if (other == com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType.getDefaultInstance()) return this;
      if (other.ageType_ != 0) {
        setAgeTypeValue(other.getAgeTypeValue());
      }
      if (other.getTravelerCount() != 0) {
        setTravelerCount(other.getTravelerCount());
      }
      if (!other.getNationality().isEmpty()) {
        nationality_ = other.nationality_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ageType_ = 0;
    /**
     * <pre>
     * 不支持指定ADT
     * </pre>
     *
     * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
     */
    public int getAgeTypeValue() {
      return ageType_;
    }
    /**
     * <pre>
     * 不支持指定ADT
     * </pre>
     *
     * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
     */
    public Builder setAgeTypeValue(int value) {
      ageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 不支持指定ADT
     * </pre>
     *
     * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
     */
    public com.ctrip.flight.intl.agg.flighttypes.v3.AgeType getAgeType() {
      @SuppressWarnings("deprecation")
      com.ctrip.flight.intl.agg.flighttypes.v3.AgeType result = com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.valueOf(ageType_);
      return result == null ? com.ctrip.flight.intl.agg.flighttypes.v3.AgeType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 不支持指定ADT
     * </pre>
     *
     * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
     */
    public Builder setAgeType(com.ctrip.flight.intl.agg.flighttypes.v3.AgeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      ageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 不支持指定ADT
     * </pre>
     *
     * <code>.com.ctrip.flight.intl.agg.flighttypes.v3.AgeType AgeType = 1;</code>
     */
    public Builder clearAgeType() {
      
      ageType_ = 0;
      onChanged();
      return this;
    }

    private int travelerCount_ ;
    /**
     * <code>int32 TravelerCount = 2;</code>
     */
    public int getTravelerCount() {
      return travelerCount_;
    }
    /**
     * <code>int32 TravelerCount = 2;</code>
     */
    public Builder setTravelerCount(int value) {
      
      travelerCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 TravelerCount = 2;</code>
     */
    public Builder clearTravelerCount() {
      
      travelerCount_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object nationality_ = "";
    /**
     * <code>string Nationality = 3;</code>
     */
    public java.lang.String getNationality() {
      java.lang.Object ref = nationality_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nationality_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Nationality = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNationalityBytes() {
      java.lang.Object ref = nationality_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nationality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Nationality = 3;</code>
     */
    public Builder setNationality(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nationality_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Nationality = 3;</code>
     */
    public Builder clearNationality() {
      
      nationality_ = getDefaultInstance().getNationality();
      onChanged();
      return this;
    }
    /**
     * <code>string Nationality = 3;</code>
     */
    public Builder setNationalityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nationality_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType)
  private static final com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType();
  }

  public static com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TravelerRequestType>
      PARSER = new com.google.protobuf.AbstractParser<TravelerRequestType>() {
    @java.lang.Override
    public TravelerRequestType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TravelerRequestType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TravelerRequestType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TravelerRequestType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.flight.intl.agg.flighttypes.v3.TravelerRequestType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

