// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

/**
 * Protobuf enum {@code com.ctrip.flight.intl.agg.flighttypes.v3.TravelerEligibilityCodeType}
 */
public enum TravelerEligibilityCodeType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *Adult
   * </pre>
   *
   * <code>ADT = 0;</code>
   */
  ADT(0),
  /**
   * <pre>
   *Accompanied Child
   * </pre>
   *
   * <code>CNN = 1;</code>
   */
  CNN(1),
  /**
   * <pre>
   *Infant without a Seat
   * </pre>
   *
   * <code>INF = 2;</code>
   */
  INF(2),
  /**
   * <pre>
   *Student
   * </pre>
   *
   * <code>STU = 3;</code>
   */
  STU(3),
  /**
   * <pre>
   *Youth Confirmed
   * </pre>
   *
   * <code>YTH = 4;</code>
   */
  YTH(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *Adult
   * </pre>
   *
   * <code>ADT = 0;</code>
   */
  public static final int ADT_VALUE = 0;
  /**
   * <pre>
   *Accompanied Child
   * </pre>
   *
   * <code>CNN = 1;</code>
   */
  public static final int CNN_VALUE = 1;
  /**
   * <pre>
   *Infant without a Seat
   * </pre>
   *
   * <code>INF = 2;</code>
   */
  public static final int INF_VALUE = 2;
  /**
   * <pre>
   *Student
   * </pre>
   *
   * <code>STU = 3;</code>
   */
  public static final int STU_VALUE = 3;
  /**
   * <pre>
   *Youth Confirmed
   * </pre>
   *
   * <code>YTH = 4;</code>
   */
  public static final int YTH_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TravelerEligibilityCodeType valueOf(int value) {
    return forNumber(value);
  }

  public static TravelerEligibilityCodeType forNumber(int value) {
    switch (value) {
      case 0: return ADT;
      case 1: return CNN;
      case 2: return INF;
      case 3: return STU;
      case 4: return YTH;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TravelerEligibilityCodeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TravelerEligibilityCodeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TravelerEligibilityCodeType>() {
          public TravelerEligibilityCodeType findValueByNumber(int number) {
            return TravelerEligibilityCodeType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.ctrip.flight.intl.agg.flighttypes.v3.AggFlighttypesV3.getDescriptor().getEnumTypes().get(1);
  }

  private static final TravelerEligibilityCodeType[] VALUES = values();

  public static TravelerEligibilityCodeType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TravelerEligibilityCodeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.ctrip.flight.intl.agg.flighttypes.v3.TravelerEligibilityCodeType)
}

