// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agg.flighttypes.v3.proto

package com.ctrip.flight.intl.agg.flighttypes.v3;

public interface VirtualFlightRemarkTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.intl.agg.flighttypes.v3.VirtualFlightRemarkType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 SegmentNo = 1;</code>
   */
  int getSegmentNo();

  /**
   * <code>int32 SequenceNo = 2;</code>
   */
  int getSequenceNo();

  /**
   * <code>string CheckInRemarkID = 3;</code>
   */
  java.lang.String getCheckInRemarkID();
  /**
   * <code>string CheckInRemarkID = 3;</code>
   */
  com.google.protobuf.ByteString
      getCheckInRemarkIDBytes();

  /**
   * <code>string PreTransRemarkID = 4;</code>
   */
  java.lang.String getPreTransRemarkID();
  /**
   * <code>string PreTransRemarkID = 4;</code>
   */
  com.google.protobuf.ByteString
      getPreTransRemarkIDBytes();

  /**
   * <code>string NextTransRemarkID = 5;</code>
   */
  java.lang.String getNextTransRemarkID();
  /**
   * <code>string NextTransRemarkID = 5;</code>
   */
  com.google.protobuf.ByteString
      getNextTransRemarkIDBytes();
}
